import Foundation

enum ResourceLibrary {
    static let all: [ResourceCard] = paperCards + methodCards + theoryCards + legacyCards

    static let paperCards: [ResourceCard] = [
        ResourceCard(
            id: "paper-wicked-problem-framing",
            title: "Wicked Problem Framing",
            type: .paper,
            relatedStages: [1, 2, 3],
            tags: ["wicked problem", "问题框定", "设计问题", "模糊", "取舍", "边界"],
            summary: "复杂设计问题通常没有唯一正确定义，问题框定本身就是设计判断的一部分。",
            whyRelevant: "当项目还像一个大主题而不是可行动的问题时，需要先决定从哪个用户、场景和限制切入。",
            howToUse: "把用户的模糊主题转成一个可验证的问题框架，并追问这个框架会排除哪些方向。",
            triggerProblem: "项目是开放主题，缺少可推进的问题框定",
            coreIdea: "复杂设计问题需要通过框定来形成行动边界，而不是等待完整事实出现",
            agentUse: "帮助 Agent 把“想做什么”转成“先框定哪一个用户场景和痛点”",
            displayText: "复杂设计问题通常要先选一个切入框架，后续功能和指标才会有依据。",
            exampleQuestion: "如果只能先框定一个最值得推进的用户场景，你会选择哪一类人和哪一刻的问题？",
            processAction: "框定复杂问题",
            authors: "Rittel & Webber",
            year: 1973,
            venue: "Policy Sciences",
            citation: "Rittel & Webber, 1973, Policy Sciences",
            researchInsight: "Wicked problems 的定义会随解决尝试改变，因此早期需要显式说明当前采用的框架。",
            designImplication: "设计澄清应优先让学生说清楚当前采用的用户、场景和取舍，而不是追求一次性完整答案。",
            ragUse: "转译成一条线索：当前最关键的是先选择一个可行动的问题框架。",
            evidenceNote: "这是问题框定理论的经典来源，适合支持 Stage 1-3 的澄清追问。",
            confidenceHint: "经典理论，需按课程项目情境转化使用。",
            cardRole: .content,
            source: "Dilemmas in a General Theory of Planning",
            sourceType: "research_paper",
            evidenceLevel: .adapted,
            problemTypes: ["topic_not_problem", "problem_too_broad", "solution_without_problem", "scope_expansion"],
            relatedFields: [.targetUser, .painPoint, .useScenario, .boundaryItems],
            priority: 126,
            uiOutputs: ["ragEvidence", "learningTrace", "processLog"]
        ),
        ResourceCard(
            id: "paper-reflective-practice",
            title: "Reflective Practice",
            type: .paper,
            relatedStages: [1, 2, 8, 9],
            tags: ["反思", "reflection", "设计判断", "行动中反思", "学习"],
            summary: "设计者常在行动中通过反思修正问题理解，而不是按固定步骤线性推进。",
            whyRelevant: "当用户说不确定或回答很浅时，反思型追问能帮助他看见自己正在做的判断。",
            howToUse: "先复述当前判断，再追问它背后的依据、例外或下一步验证方式。",
            triggerProblem: "用户卡住，无法说明自己当前判断的依据",
            coreIdea: "设计学习来自对行动和结果的持续反思",
            agentUse: "帮助 Agent 把卡住状态转成可回答的反思问题",
            displayText: "当你不确定时，可以先看清自己已经做了哪个判断，以及它还缺什么依据。",
            exampleQuestion: "你现在最愿意先相信的一个判断是什么，它还缺哪种证据支持？",
            processAction: "促发反思判断",
            authors: "Schön",
            year: 1983,
            venue: "Basic Books",
            citation: "Schön, 1983",
            researchInsight: "Reflective practice 强调专业判断在行动与反思之间循环形成。",
            designImplication: "Agent 不应直接给答案，而应帮助用户把隐含判断说出来并准备验证。",
            ragUse: "在 stuckScaffold 中给出线索：先承认不确定，再找出当前最小判断。",
            evidenceNote: "经典反思实践理论，适合支持学习轨迹和思维树记录。",
            confidenceHint: "经典理论，适合教学语境。",
            cardRole: .scaffoldingStrategy,
            source: "The Reflective Practitioner",
            sourceType: "research_book",
            evidenceLevel: .adapted,
            problemTypes: ["user_stuck", "answer_too_shallow", "claim_without_evidence", "next_step_unclear"],
            relatedFields: [.coreValue, .risks, .milestones],
            priority: 118,
            uiOutputs: ["ragEvidence", "methodHint", "learningTrace"]
        ),
        ResourceCard(
            id: "paper-designerly-ways",
            title: "Designerly Ways of Knowing",
            type: .paper,
            relatedStages: [1, 2, 4],
            tags: ["designerly", "设计认知", "原型", "方案", "问题空间", "solution first"],
            summary: "设计思维通过问题和方案的共同演化形成知识，原型可以用来澄清问题本身。",
            whyRelevant: "当用户只列功能或方案时，需要追问这些方案正在假设怎样的问题。",
            howToUse: "把功能点反推为用户任务、问题假设和可验证的设计判断。",
            triggerProblem: "用户从方案或功能开始，但问题假设还不清楚",
            coreIdea: "设计问题和设计方案往往共同演化，方案能反过来暴露问题理解",
            agentUse: "帮助 Agent 从功能描述反推用户任务和问题假设",
            displayText: "功能不是终点，它也能反过来暴露你真正相信的问题是什么。",
            exampleQuestion: "这些功能背后，你最希望验证的用户问题是哪一个？",
            processAction: "从方案反推问题",
            authors: "Cross",
            year: 1982,
            venue: "Design Studies",
            citation: "Cross, 1982, Design Studies",
            researchInsight: "Designerly knowing 强调设计者通过构造和评估方案来形成问题知识。",
            designImplication: "当学生先说方案时，Agent 应把方案转成问题假设，而不是否定方案起点。",
            ragUse: "转译成线索：先看功能背后的问题假设。",
            evidenceNote: "设计认知经典观点，适合连接问题澄清和功能拆解。",
            confidenceHint: "经典理论，适合设计教育转译。",
            cardRole: .questionStrategy,
            source: "Designerly Ways of Knowing",
            sourceType: "research_paper",
            evidenceLevel: .adapted,
            problemTypes: ["solution_first", "function_list_only", "solution_without_problem", "feature_without_user_outcome"],
            relatedFields: [.painPoint, .coreValue, .mvpFeatures],
            priority: 114,
            uiOutputs: ["ragEvidence", "processLog"]
        ),
        ResourceCard(
            id: "paper-design-thinking-wicked",
            title: "Design Thinking as Framing",
            type: .paper,
            relatedStages: [1, 2, 3],
            tags: ["design thinking", "problem framing", "价值", "边界", "机会点"],
            summary: "设计思维的关键不是固定流程，而是在复杂处境中重构问题、价值和行动可能性。",
            whyRelevant: "当用户把设计思维理解成填表流程时，需要回到价值、场景和边界的判断。",
            howToUse: "追问当前框架如何改变价值判断，以及它会让第一版做什么、不做什么。",
            triggerProblem: "设计阶段被机械填写，缺少价值和边界判断",
            coreIdea: "设计思维通过框定问题来组织行动，而不是只按步骤收集信息",
            agentUse: "帮助 Agent 将阶段推进与设计判断绑定",
            displayText: "设计流程不是填空，而是不断确认什么判断会改变后续方案。",
            exampleQuestion: "这个阶段里，哪一个判断一旦改变，会让你的方案方向也跟着改变？",
            processAction: "连接阶段与判断",
            authors: "Buchanan",
            year: 1992,
            venue: "Design Issues",
            citation: "Buchanan, 1992, Design Issues",
            researchInsight: "Design thinking 可被理解为在 wicked problems 中进行框定与再框定。",
            designImplication: "每轮追问都应指向一个会影响方案的设计变量。",
            ragUse: "转译成线索：本轮问题必须服务一个真实设计判断。",
            evidenceNote: "设计思维和 wicked problem 经典论述。",
            confidenceHint: "经典理论，适合作为课程框架依据。",
            cardRole: .cognitiveDepth,
            source: "Wicked Problems in Design Thinking",
            sourceType: "research_paper",
            evidenceLevel: .adapted,
            problemTypes: ["answer_too_shallow", "reasoning_too_shallow", "problem_too_broad"],
            relatedFields: [.coreValue, .differentiation, .boundaryItems],
            priority: 112,
            uiOutputs: ["ragEvidence", "learningTrace"]
        ),
        ResourceCard(
            id: "paper-research-through-design",
            title: "Research Through Design",
            type: .paper,
            relatedStages: [4, 7, 9],
            tags: ["research through design", "prototype", "原型", "验证", "评价", "artifact"],
            summary: "设计产物可以作为研究和学习的媒介，用来暴露假设、评价体验并产生可讨论证据。",
            whyRelevant: "当用户不知道怎么验证设计时，可以把第一版原型看成验证关键假设的工具。",
            howToUse: "追问第一个原型要验证哪个不确定判断，以及用什么观察结果判断有效。",
            triggerProblem: "原型和评价标准没有连接到关键假设",
            coreIdea: "原型不只是展示成果，也能生成关于问题和体验的证据",
            agentUse: "帮助 Agent 把功能拆解、验收标准和里程碑连接成验证闭环",
            displayText: "第一版原型最有价值的地方，是帮你验证一个关键假设。",
            exampleQuestion: "第一个低保真原型最应该验证哪一个关键假设，观察什么结果才算有效？",
            processAction: "定义验证型原型",
            authors: "Zimmerman, Forlizzi & Evenson",
            year: 2007,
            venue: "CHI",
            citation: "Zimmerman et al., 2007, CHI",
            researchInsight: "Research through Design 把 artifact 视为生成设计知识和讨论证据的方式。",
            designImplication: "设计训练中的评价标准应和原型要验证的假设直接相连。",
            ragUse: "转译成线索：把原型当成验证工具，而不是功能清单。",
            evidenceNote: "HCI/设计研究经典 paper，适合评价和里程碑阶段。",
            confidenceHint: "经典 HCI 论文，适合原型验证语境。",
            cardRole: .content,
            source: "Research through Design as a Method for Interaction Design Research in HCI",
            sourceType: "research_paper",
            evidenceLevel: .adapted,
            problemTypes: ["evaluation_dimensions_missing", "metric_not_linked_to_change", "next_step_unclear", "assumption_unchecked"],
            relatedFields: [.mvpFeatures, .successMetrics, .milestones],
            priority: 116,
            uiOutputs: ["ragEvidence", "processLog"]
        ),
        ResourceCard(
            id: "paper-hai-guidelines",
            title: "Human-AI Interaction Guidelines",
            type: .paper,
            relatedStages: [2, 3, 5, 8],
            tags: ["human-ai", "AI", "人工智能", "透明", "反馈", "控制", "错误", "HCI"],
            summary: "人机 AI 交互需要在合适时机说明能力、表达不确定性、支持用户控制和错误恢复。",
            whyRelevant: "当项目涉及 AI 但只把 AI 当卖点时，需要追问 AI 在流程里如何可理解、可控、可恢复。",
            howToUse: "围绕 AI 的边界、反馈、失败处理和用户控制提出澄清问题。",
            triggerProblem: "AI 产品只强调智能能力，缺少用户控制和失败处理",
            coreIdea: "AI 体验要让用户知道系统能做什么、何时不确定、如何纠错",
            agentUse: "帮助 Agent 提升 AI 边界、透明度和错误恢复相关追问权重",
            displayText: "AI 产品不只要“聪明”，还要让用户知道什么时候该信、怎么改、失败时怎么办。",
            exampleQuestion: "当 AI 判断不准时，用户能看到什么提示，并如何修改或接管？",
            processAction: "澄清 AI 可控性",
            authors: "Amershi et al.",
            year: 2019,
            venue: "CHI",
            citation: "Amershi et al., 2019, CHI",
            researchInsight: "Human-AI guidelines 强调能力边界、反馈时机、用户控制和错误恢复。",
            designImplication: "AI 项目的运行逻辑必须包含不确定性表达、可撤销和人工接管。",
            ragUse: "转译成线索：AI 的可靠体验来自边界、控制和恢复机制。",
            evidenceNote: "HCI 中常用的人机 AI 交互指南，适合 AI 产品澄清。",
            confidenceHint: "高相关 HCI 指南型论文。",
            cardRole: .content,
            source: "Guidelines for Human-AI Interaction",
            sourceType: "research_paper",
            evidenceLevel: .direct,
            problemTypes: ["ai_value_unclear", "ai_as_selling_point", "confidence_not_shown", "user_control_missing", "error_flow_missing"],
            relatedFields: [.coreValue, .boundaryItems, .operationLogic, .risks],
            requiredContext: ["project_uses_ai"],
            priority: 132,
            uiOutputs: ["ragEvidence", "methodHint", "processLog"]
        ),
        ResourceCard(
            id: "paper-mixed-initiative",
            title: "Mixed-Initiative Interaction",
            type: .paper,
            relatedStages: [3, 4, 5],
            tags: ["mixed initiative", "AI", "人机协作", "主动性", "控制权", "流程"],
            summary: "混合主动交互关注系统与用户何时分别主动，好的体验需要清晰的交接规则。",
            whyRelevant: "当用户设计 AI 助手或协作工具时，需要明确哪些判断由系统提出，哪些由人确认。",
            howToUse: "追问系统何时建议、何时等待、何时把控制权还给用户。",
            triggerProblem: "AI 或系统主动性边界不清，容易替用户做决定",
            coreIdea: "人机协作需要定义主动权切换和用户确认机制",
            agentUse: "帮助 Agent 追问流程中的人机分工和控制权",
            displayText: "AI 助手的关键不是一直主动，而是知道何时建议、何时等待用户确认。",
            exampleQuestion: "在你的流程里，哪些判断可以由系统建议，哪些必须由用户确认后才继续？",
            processAction: "定义人机主动权",
            authors: "Horvitz",
            year: 1999,
            venue: "CHI",
            citation: "Horvitz, 1999, CHI",
            researchInsight: "Mixed-initiative systems 需要基于不确定性、代价和用户目标来协调主动性。",
            designImplication: "AI 交互流程要明确主动权转移、确认和中止机制。",
            ragUse: "转译成线索：先划清系统建议和用户决定的边界。",
            evidenceNote: "混合主动交互经典观点，适合 AI 工作流与边界阶段。",
            confidenceHint: "经典 HCI paper，需结合具体 AI 场景转化。",
            cardRole: .questionStrategy,
            source: "Principles of Mixed-Initiative User Interfaces",
            sourceType: "research_paper",
            evidenceLevel: .adapted,
            problemTypes: ["user_control_missing", "interaction_flow_missing", "feedback_missing", "ai_value_unclear"],
            relatedFields: [.boundaryItems, .interactionFlow, .operationLogic],
            requiredContext: ["project_uses_ai"],
            priority: 124,
            uiOutputs: ["ragEvidence", "processLog"]
        ),
        ResourceCard(
            id: "paper-human-centered-ai-control",
            title: "Human-Centered AI Control",
            type: .paper,
            relatedStages: [3, 5, 6, 8],
            tags: ["human-centered ai", "AI", "人工介入", "控制", "安全", "边界", "风险"],
            summary: "以人为中心的 AI 强调可靠、安全、可信，并保留人的监督、控制和责任边界。",
            whyRelevant: "当 AI 产品影响真实决策时，需要明确人何时介入、责任如何分配、哪些自动化不能做。",
            howToUse: "追问自动化边界、人工审核节点和失败后的责任处理。",
            triggerProblem: "AI 自动化范围过大，缺少人类监督和责任边界",
            coreIdea: "AI 系统应提升人的能力，同时保留可监督、可中止、可追责的控制结构",
            agentUse: "帮助 Agent 在边界、约束和风险阶段提升 HITL 追问",
            displayText: "涉及 AI 决策时，第一版要清楚哪些环节必须由人确认或接管。",
            exampleQuestion: "哪一个 AI 决策绝对不能自动完成，必须保留人工确认或撤销？",
            processAction: "划定 AI 自动化边界",
            authors: "Shneiderman",
            year: 2020,
            venue: "International Journal of Human-Computer Interaction",
            citation: "Shneiderman, 2020, IJHCI",
            researchInsight: "Human-centered AI 强调可靠性、安全性、可信任和人的监督控制。",
            designImplication: "AI 产品需要把 HITL 节点写进流程和风险预案，而不是只写模型能力。",
            ragUse: "转译成线索：先决定哪些判断必须由人保留控制权。",
            evidenceNote: "以人为中心 AI 观点，适合 AI 边界与风险澄清。",
            confidenceHint: "高相关理论，适合 AI 产品取舍。",
            cardRole: .content,
            source: "Human-Centered Artificial Intelligence",
            sourceType: "research_paper",
            evidenceLevel: .adapted,
            problemTypes: ["user_control_missing", "scope_expansion", "risk_missing", "constraint_ignored"],
            relatedFields: [.boundaryItems, .operationLogic, .hardConstraints, .risks],
            requiredContext: ["project_uses_ai"],
            priority: 128,
            uiOutputs: ["ragEvidence", "learningTrace"]
        ),
        ResourceCard(
            id: "paper-ai-explainability",
            title: "Explainability as User Understanding",
            type: .paper,
            relatedStages: [5, 7, 8],
            tags: ["explainability", "解释", "透明", "信任", "AI", "依据"],
            summary: "可解释性不只是展示模型细节，而是帮助用户形成足够正确的理解来行动。",
            whyRelevant: "当用户说要展示 AI 依据时，需要追问展示什么解释才真正帮助用户判断和纠错。",
            howToUse: "追问解释对象、解释时机和用户看完后能做什么。",
            triggerProblem: "AI 解释只停留在展示理由，未连接用户行动",
            coreIdea: "解释的价值在于支持用户理解、判断、纠错和校准信任",
            agentUse: "帮助 Agent 把“可解释”转成具体反馈和评价标准",
            displayText: "解释不是越多越好，而是要让用户知道下一步该相信、修改还是接管。",
            exampleQuestion: "用户看完 AI 的解释后，应该能做出哪一个更好的判断或修正？",
            processAction: "定义解释的用途",
            authors: "Abdul et al.",
            year: 2018,
            venue: "CHI",
            citation: "Abdul et al., 2018, CHI",
            researchInsight: "XAI 与 HCI 的交汇强调解释应服务用户目标、理解和行动。",
            designImplication: "AI 解释需要和用户任务、反馈时机、纠错机制、成功指标相连。",
            ragUse: "转译成线索：先问解释要帮助用户完成什么判断。",
            evidenceNote: "HCI/XAI 综述型论文，适合透明度与评价阶段。",
            confidenceHint: "高相关综述，适合 HCI 设计转译。",
            cardRole: .questionStrategy,
            source: "Trends and Trajectories for Explainable, Accountable and Intelligible Systems",
            sourceType: "research_paper",
            evidenceLevel: .adapted,
            problemTypes: ["confidence_not_shown", "feedback_missing", "evaluation_dimensions_missing", "ai_value_unclear"],
            relatedFields: [.operationLogic, .successMetrics, .risks],
            requiredContext: ["project_uses_ai"],
            priority: 122,
            uiOutputs: ["ragEvidence", "processLog"]
        ),
        ResourceCard(
            id: "paper-uncertainty-communication",
            title: "Uncertainty Communication",
            type: .paper,
            relatedStages: [5, 7, 8],
            tags: ["uncertainty", "不确定性", "置信度", "AI", "风险", "透明"],
            summary: "把不确定性可视化或可感知地表达出来，能帮助用户校准预期并做出更合适的判断。",
            whyRelevant: "当系统判断存在概率、推荐或 AI 置信度时，需要明确如何表达不确定，而不是假装确定。",
            howToUse: "追问系统在哪些节点会不确定，用户看到后如何调整行动。",
            triggerProblem: "系统或 AI 输出看起来过于确定，用户无法判断风险",
            coreIdea: "不确定性表达能帮助用户理解预测或建议的可靠范围",
            agentUse: "帮助 Agent 追问置信度、风险提示和用户决策校准",
            displayText: "如果系统本身不确定，界面也应该让用户知道不确定在哪里。",
            exampleQuestion: "当系统不确定时，用户会看到什么信号，并据此怎样调整下一步？",
            processAction: "表达系统不确定性",
            authors: "Kay et al.",
            year: 2016,
            venue: "CHI",
            citation: "Kay et al., 2016, CHI",
            researchInsight: "面向用户的不确定性表达可以影响理解、信任和行动选择。",
            designImplication: "AI/推荐/预测类设计应把不确定性表达纳入运行逻辑和评价标准。",
            ragUse: "转译成线索：先找出系统最容易不确定的节点。",
            evidenceNote: "不确定性沟通 HCI paper，适合 AI 透明度和风险阶段。",
            confidenceHint: "相关 HCI 证据，需按具体界面转译。",
            cardRole: .content,
            source: "When(ish) is My Bus?",
            sourceType: "research_paper",
            evidenceLevel: .adapted,
            problemTypes: ["confidence_not_shown", "error_flow_missing", "risk_missing", "evaluation_dimensions_missing"],
            relatedFields: [.operationLogic, .successMetrics, .risks],
            requiredContext: ["project_uses_ai"],
            priority: 120,
            uiOutputs: ["ragEvidence", "methodHint"]
        ),
        ResourceCard(
            id: "paper-automation-bias",
            title: "Automation Bias",
            type: .paper,
            relatedStages: [3, 5, 8],
            tags: ["automation bias", "自动化偏误", "AI", "过度信任", "风险", "控制"],
            summary: "用户可能过度依赖自动化建议，忽略错误或放弃自己的判断。",
            whyRelevant: "当方案让 AI 自动推荐、评分或决策时，需要设计防止盲目信任的反馈和接管机制。",
            howToUse: "追问用户如何发现系统可能错了，以及何时需要人工复核。",
            triggerProblem: "自动化建议可能让用户过度信任或放弃判断",
            coreIdea: "自动化会改变人的注意和责任分配，错误时可能被忽略",
            agentUse: "帮助 Agent 在 AI 风险和控制权场景中追问纠错机制",
            displayText: "自动化越强，越需要设计用户发现错误和重新接管的机会。",
            exampleQuestion: "用户怎样发现 AI 建议可能错了，并在那一刻重新接管判断？",
            processAction: "防止自动化偏误",
            authors: "Parasuraman & Riley",
            year: 1997,
            venue: "Human Factors",
            citation: "Parasuraman & Riley, 1997, Human Factors",
            researchInsight: "Automation bias 指人对自动化建议的误用或过度依赖。",
            designImplication: "AI 产品需要设计校准信任、错误提示和人工复核，而不是默认用户总会理性检查。",
            ragUse: "转译成线索：先问用户何时会过度相信系统。",
            evidenceNote: "自动化与人因经典研究，适合 AI 风险阶段。",
            confidenceHint: "经典人因研究，适合风险转译。",
            cardRole: .cognitiveDepth,
            source: "Humans and Automation: Use, Misuse, Disuse, Abuse",
            sourceType: "research_paper",
            evidenceLevel: .adapted,
            problemTypes: ["user_control_missing", "mistake_recovery_missing", "risk_missing", "ai_value_unclear"],
            relatedFields: [.boundaryItems, .operationLogic, .risks],
            requiredContext: ["project_uses_ai"],
            priority: 118,
            uiOutputs: ["ragEvidence", "learningTrace"]
        ),
        ResourceCard(
            id: "paper-cognitive-load-scaffolding",
            title: "Cognitive Load and Scaffolding",
            type: .paper,
            relatedStages: [1, 2, 4, 9],
            tags: ["scaffolding", "cognitive load", "认知负荷", "卡住", "学习", "提问"],
            summary: "当学习者面对复杂任务时，合适的脚手架应降低无关负荷，同时保留核心思考责任。",
            whyRelevant: "当用户说不知道怎么答时，Agent 应提供线索和问题，而不是给完整答案或选项。",
            howToUse: "把大问题拆成一个能回答的小判断，并说明为什么这个判断重要。",
            triggerProblem: "用户被复杂问题压住，无法开始回答",
            coreIdea: "脚手架应降低进入门槛，但不替代学习者完成核心判断",
            agentUse: "帮助 Agent 在 stuckScaffold 中给线索、只问一个问题、避免 A/B/C",
            displayText: "卡住时可以先降到一个小判断，但这个判断仍然要由你自己完成。",
            exampleQuestion: "先不用完整回答，当前只要判断：哪一个用户场景最值得第一版先验证？",
            processAction: "降低认知负荷",
            authors: "Sweller",
            year: 1988,
            venue: "Cognitive Science",
            citation: "Sweller, 1988, Cognitive Science",
            researchInsight: "认知负荷理论提醒复杂任务需要控制信息负荷与任务拆分。",
            designImplication: "Agent 应把复杂澄清拆成短线索和单一开放问题，避免一次给多个选项。",
            ragUse: "转译成线索：先把问题缩小到一个可回答判断。",
            evidenceNote: "学习科学经典理论，适合 stuckScaffold 和教学场景。",
            confidenceHint: "经典学习理论，需结合设计训练任务转译。",
            cardRole: .scaffoldingStrategy,
            source: "Cognitive Load During Problem Solving",
            sourceType: "research_paper",
            evidenceLevel: .adapted,
            problemTypes: ["user_stuck", "answer_too_shallow", "asks_for_example", "next_step_unclear"],
            relatedFields: [.targetUser, .coreValue, .mvpFeatures, .milestones],
            priority: 130,
            uiOutputs: ["ragEvidence", "methodHint", "learningTrace"]
        ),
        ResourceCard(
            id: "paper-scaffolding-learning",
            title: "Scaffolding by Questioning",
            type: .paper,
            relatedStages: [1, 2, 8, 9],
            tags: ["scaffold", "提问", "学习", "反思", "zone", "卡住"],
            summary: "有效脚手架会暂时支持学习者完成原本无法独立完成的思考，并逐步把控制权还给学习者。",
            whyRelevant: "当用户请求帮助时，系统应给可理解线索，再让用户继续做判断。",
            howToUse: "先指出当前缺口，再问一个能让用户自己补上的开放问题。",
            triggerProblem: "用户需要帮助开始思考，但仍应保持自主判断",
            coreIdea: "脚手架不是答案替代，而是让学习者能继续完成下一步思考",
            agentUse: "帮助 Agent 形成隐式三段流中的线索和提问顺序",
            displayText: "好的帮助不是替你回答，而是让你更容易回答下一步。",
            exampleQuestion: "如果先只补一个缺口，哪个信息会让这个设计判断更清楚？",
            processAction: "用提问搭建脚手架",
            authors: "Wood, Bruner & Ross",
            year: 1976,
            venue: "Journal of Child Psychology and Psychiatry",
            citation: "Wood et al., 1976",
            researchInsight: "Scaffolding 通过临时支持帮助学习者完成超出当前独立能力的任务。",
            designImplication: "CoDesign 的帮助应表现为线索加问题，而不是完整答案或选择题。",
            ragUse: "转译成线索：先降低入口，再把判断权交还用户。",
            evidenceNote: "脚手架经典理论，适合教学型对话策略。",
            confidenceHint: "经典学习理论，适合教学转译。",
            cardRole: .scaffoldingStrategy,
            source: "The Role of Tutoring in Problem Solving",
            sourceType: "research_paper",
            evidenceLevel: .adapted,
            problemTypes: ["user_stuck", "asks_for_example", "binary_judgment", "answer_too_shallow"],
            relatedFields: [.painPoint, .coreValue, .risks, .milestones],
            priority: 126,
            uiOutputs: ["ragEvidence", "methodHint"]
        ),
        ResourceCard(
            id: "paper-goodhart-success-metrics",
            title: "Goodhart and Success Metrics",
            type: .paper,
            relatedStages: [7, 8],
            tags: ["metrics", "success metrics", "指标", "评价", "goodhart", "量化", "验收"],
            summary: "当指标变成目标本身时，系统可能优化数字却偏离真实价值。",
            whyRelevant: "当用户只说点击率、完成率等数字时，需要追问这些指标是否真的代表用户改善。",
            howToUse: "把每个指标连接到用户状态改变，并检查可能被刷高或误导的风险。",
            triggerProblem: "成功指标和真实价值脱节，或指标容易被误优化",
            coreIdea: "指标必须代表真实改善，否则会诱导错误优化",
            agentUse: "帮助 Agent 在评价阶段追问指标、行为证据和反指标",
            displayText: "好指标不只是数字好看，而是能代表用户真的变好了。",
            exampleQuestion: "哪个可观察指标最能代表用户状态真的改善，而不是只让数字变好看？",
            processAction: "校准成功指标",
            authors: "Goodhart",
            year: 1975,
            venue: "Monetary Policy Papers",
            citation: "Goodhart, 1975",
            researchInsight: "Goodhart's Law 提醒被用作目标的指标可能失去原本的信息价值。",
            designImplication: "设计评价要连接用户改变、观测方法和潜在误导风险。",
            ragUse: "转译成线索：先确认指标代表的真实用户变化。",
            evidenceNote: "指标风险经典理论，适合 Stage 7-8。",
            confidenceHint: "经典原则，适合评价指标反思。",
            cardRole: .cognitiveDepth,
            source: "Problems of Monetary Management",
            sourceType: "theory",
            evidenceLevel: .heuristic,
            problemTypes: ["evaluation_dimensions_missing", "metric_not_linked_to_change", "risk_missing", "claim_without_evidence"],
            relatedFields: [.successMetrics, .risks],
            priority: 124,
            uiOutputs: ["ragEvidence", "learningTrace"]
        )
    ]

    static let methodCards: [ResourceCard] = [
        ResourceCard(
            id: "method-persona",
            title: "Persona / 用户画像",
            type: .method,
            relatedStages: [1],
            tags: ["用户", "目标用户", "画像", "大学生", "人群", "泛化"],
            summary: "用一个代表性用户承载目标、动机、限制和情境，避免设计对象过于宽泛。",
            whyRelevant: "当前目标用户如果还停留在“大众、学生、用户”等泛称，后续功能取舍会失去依据。",
            howToUse: "把宽泛人群收敛为一个优先服务的典型角色，并说明他的任务、限制和场景。",
            triggerProblem: "用户对象过泛，无法支持方案取舍",
            coreIdea: "用代表性用户画像承载目标、动机、行为和限制",
            agentUse: "帮助 Agent 将模糊用户群拆成具体的典型角色",
            displayText: "当用户太宽泛时，Persona 能帮我们先选一个具体的人来设计。",
            exampleQuestion: "这个方案最先服务的典型用户是谁？",
            processAction: "聚焦目标用户",
            cardRole: .content,
            source: "User-centered design method",
            sourceType: "design_method",
            evidenceLevel: .adapted,
            problemTypes: ["user_too_broad", "target_user_missing", "solution_first"],
            relatedFields: [.targetUser],
            priority: 120,
            uiOutputs: ["methodHint", "learningTrace", "processLog"]
        ),
        ResourceCard(
            id: "method-empathy-map",
            title: "Empathy Map / 共情地图",
            type: .method,
            relatedStages: [1],
            tags: ["共情", "用户", "感受", "行为", "动机"],
            summary: "从用户看到、听到、想到、感到和实际做什么来理解真实处境。",
            whyRelevant: "当用户只描述需求结论时，共情地图能帮助补齐用户处境和动机。",
            howToUse: "围绕一个具体用户写出他在场景中想什么、担心什么、实际怎么做。",
            triggerProblem: "用户处境和动机缺失",
            coreIdea: "通过多维线索理解用户真实体验",
            agentUse: "帮助 Agent 从抽象需求转向用户处境、感受和行为",
            displayText: "共情地图帮助我们理解用户为什么会这样做，而不只是他说需要什么。",
            exampleQuestion: "这个用户在当时最担心什么、实际会怎么处理？",
            processAction: "补充用户处境",
            cardRole: .content,
            source: "Design thinking method",
            sourceType: "design_method",
            evidenceLevel: .adapted,
            problemTypes: ["user_context_missing", "motivation_missing"],
            relatedFields: [.targetUser, .painPoint, .useScenario],
            priority: 102,
            uiOutputs: ["methodHint", "processLog"]
        ),
        ResourceCard(
            id: "method-user-journey-map",
            title: "User Journey Map / 用户旅程图",
            type: .method,
            relatedStages: [1, 4],
            tags: ["旅程", "流程", "场景", "触点", "痛点", "交互"],
            summary: "按时间线梳理用户行为、触点、情绪和痛点，找出关键干预点。",
            whyRelevant: "当只有功能点或场景缺失时，旅程图能把问题放回完整使用流程。",
            howToUse: "列出使用前、使用中、使用后的关键步骤，并标出最容易卡住的一步。",
            triggerProblem: "缺少具体场景或完整使用流程",
            coreIdea: "用时间线连接行为、触点和痛点",
            agentUse: "帮助 Agent 追问用户从开始到完成任务经历哪些关键步骤",
            displayText: "用户旅程图帮助我们看清问题发生在流程中的哪一刻。",
            exampleQuestion: "从用户第一次打开产品到完成任务，中间会经历哪些关键步骤？",
            processAction: "拆解使用流程",
            cardRole: .content,
            source: "Service design method",
            sourceType: "design_method",
            evidenceLevel: .adapted,
            problemTypes: ["scenario_missing", "interaction_flow_missing", "feature_not_decomposed"],
            relatedFields: [.useScenario, .interactionFlow, .painPoint],
            priority: 112,
            uiOutputs: ["methodHint", "processLog"]
        ),
        ResourceCard(
            id: "method-five-whys",
            title: "5 Whys / 五问法",
            type: .method,
            relatedStages: [1, 8],
            tags: ["为什么", "原因", "痛点", "风险", "根因"],
            summary: "通过连续追问原因，从表层现象下探到更深层的痛点或风险根因。",
            whyRelevant: "当用户只给出现象或乐观判断时，需要继续追问背后的原因。",
            howToUse: "围绕一个痛点或风险连续追问“为什么”，直到出现可设计介入的原因。",
            triggerProblem: "用户只给出现象或表层原因",
            coreIdea: "从现象追到可行动的深层原因",
            agentUse: "帮助 Agent 通过连续追问找到更深层痛点或风险根因",
            displayText: "五问法帮助我们从表面现象继续挖到真正原因。",
            exampleQuestion: "为什么这个问题会反复发生？",
            processAction: "挖掘深层原因",
            cardRole: .content,
            source: "Root cause analysis method",
            sourceType: "design_method",
            evidenceLevel: .adapted,
            problemTypes: ["pain_point_missing", "reasoning_too_shallow", "risk_cause_unclear"],
            relatedFields: [.painPoint, .risks],
            priority: 106,
            uiOutputs: ["methodHint", "learningTrace", "processLog"]
        ),
        ResourceCard(
            id: "method-problem-statement",
            title: "Problem Statement / 问题陈述",
            type: .method,
            relatedStages: [1],
            tags: ["问题陈述", "用户", "痛点", "场景", "定义"],
            summary: "把设计方向压缩成“谁在什么场景下遇到什么困难”的清晰表述。",
            whyRelevant: "当项目只有主题或方案时，问题陈述能帮助形成可推进的问题边界。",
            howToUse: "使用“为[用户]在[场景]中解决[痛点]”重写当前项目。",
            triggerProblem: "只有主题或方案，没有清楚问题定义",
            coreIdea: "把混乱方向框定成可讨论的问题",
            agentUse: "帮助 Agent 将模糊方向转成目标用户、场景和痛点",
            displayText: "问题陈述帮助我们把想法变成可以继续推进的问题。",
            exampleQuestion: "我们能否把这个方向改写成：谁在什么场景下遇到什么困难？",
            processAction: "形成问题陈述",
            cardRole: .content,
            source: "Design framing method",
            sourceType: "design_method",
            evidenceLevel: .adapted,
            problemTypes: ["topic_not_problem", "problem_too_broad", "solution_without_problem"],
            relatedFields: [.targetUser, .painPoint, .useScenario],
            priority: 104,
            uiOutputs: ["methodHint", "processLog"]
        ),
        ResourceCard(
            id: "method-how-might-we",
            title: "How Might We / 我们如何",
            type: .method,
            relatedStages: [1, 2],
            tags: ["机会点", "问题", "价值", "开放问题", "HMW"],
            summary: "把痛点改写成开放但有边界的设计机会，避免过早锁死方案。",
            whyRelevant: "当用户把问题说成结论或价值方向不清时，可以用 HMW 重新打开设计空间。",
            howToUse: "用“我们如何帮助[用户]在[场景]中改善[痛点/状态]”组织机会点。",
            triggerProblem: "问题被说成结论，或方案过早固定",
            coreIdea: "用开放问题保留探索空间，同时保留用户和场景边界",
            agentUse: "帮助 Agent 将痛点转成可探索的设计机会",
            displayText: "How Might We 把痛点变成一个有边界的机会问题。",
            exampleQuestion: "我们如何帮助这类用户在这个场景里更容易完成关键任务？",
            processAction: "转化设计机会",
            cardRole: .content,
            source: "Design thinking method",
            sourceType: "design_method",
            evidenceLevel: .adapted,
            problemTypes: ["problem_as_solution", "solution_first", "value_too_abstract"],
            relatedFields: [.painPoint, .useScenario, .coreValue],
            priority: 98,
            uiOutputs: ["methodHint", "processLog"]
        ),
        ResourceCard(
            id: "method-jobs-to-be-done",
            title: "Jobs To Be Done / 用户任务",
            type: .method,
            relatedStages: [2],
            tags: ["任务", "价值", "功能", "JTBD", "动机"],
            summary: "从用户真正想完成的任务理解产品价值，而不是只看功能清单。",
            whyRelevant: "当用户只描述功能时，需要追问这些功能背后想帮助用户完成什么任务。",
            howToUse: "区分用户想完成的功能操作、情境任务和最终结果。",
            triggerProblem: "用户在描述功能，但没有说明真正要完成的任务",
            coreIdea: "产品价值来自用户要完成的任务和状态改变",
            agentUse: "帮助 Agent 从功能清单追问到用户任务和核心价值",
            displayText: "JTBD 帮助我们从“做什么功能”转向“用户真正要完成什么”。",
            exampleQuestion: "这些功能背后，用户真正想完成的任务是什么？",
            processAction: "提炼用户任务",
            cardRole: .content,
            source: "Jobs To Be Done framework",
            sourceType: "design_method",
            evidenceLevel: .adapted,
            problemTypes: ["feature_without_user_outcome", "value_too_abstract", "function_list_only"],
            relatedFields: [.coreValue, .differentiation],
            priority: 118,
            uiOutputs: ["methodHint", "learningTrace", "processLog"]
        ),
        ResourceCard(
            id: "method-insight-statement",
            title: "Insight Statement / 洞察陈述",
            type: .method,
            relatedStages: [2],
            tags: ["洞察", "价值", "差异化", "用户理解"],
            summary: "把观察到的用户行为和背后原因压缩成一句可指导方案的洞察。",
            whyRelevant: "当价值主张还停留在口号时，需要形成更有解释力的用户洞察。",
            howToUse: "用“用户需要 X，因为 Y”表达一个能指导方案的判断。",
            triggerProblem: "价值主张停留在口号或形容词",
            coreIdea: "洞察连接用户行为、原因和设计机会",
            agentUse: "帮助 Agent 追问用户为什么需要这个价值",
            displayText: "洞察陈述帮助我们说明价值为什么成立。",
            exampleQuestion: "用户为什么会需要这个价值，而不是继续用现在的办法？",
            processAction: "形成用户洞察",
            cardRole: .content,
            source: "Design research synthesis method",
            sourceType: "design_method",
            evidenceLevel: .adapted,
            problemTypes: ["value_too_abstract", "differentiation_missing"],
            relatedFields: [.coreValue, .differentiation],
            priority: 108,
            uiOutputs: ["methodHint", "processLog"]
        ),
        ResourceCard(
            id: "method-assumption-mapping",
            title: "Assumption Mapping / 假设地图",
            type: .method,
            relatedStages: [2, 3, 5, 6, 8],
            tags: ["假设", "风险", "边界", "可行性", "验证"],
            summary: "把项目未知判断按重要性和不确定性排序，优先处理高风险假设。",
            whyRelevant: "当方案依赖未经验证的前提时，需要先识别并验证关键假设。",
            howToUse: "列出关键假设，优先验证“影响大且不确定”的一项。",
            triggerProblem: "方案依赖大量未经验证的前提",
            coreIdea: "用重要性和不确定性判断哪个假设最该先验证",
            agentUse: "帮助 Agent 将风险、边界和技术不确定性转成可验证假设",
            displayText: "假设地图帮助我们看清哪些判断还没有证据支撑。",
            exampleQuestion: "这个方案最关键、但现在还没证据的假设是什么？",
            processAction: "识别关键假设",
            cardRole: .content,
            source: "Lean product discovery method",
            sourceType: "design_method",
            evidenceLevel: .adapted,
            problemTypes: ["assumption_unchecked", "risk_missing", "constraint_ignored", "ai_value_unclear"],
            relatedFields: [.boundaryItems, .hardConstraints, .risks, .coreValue],
            priority: 110,
            uiOutputs: ["methodHint", "learningTrace", "processLog"]
        ),
        ResourceCard(
            id: "method-concept-testing",
            title: "Concept Testing / 概念测试",
            type: .method,
            relatedStages: [2, 7],
            tags: ["概念", "验证", "价值", "测试", "理解"],
            summary: "用轻量概念表达测试用户是否理解、是否认为有价值、是否愿意使用。",
            whyRelevant: "当价值主张还没有外部验证时，需要设计低成本概念测试。",
            howToUse: "用一句话或一个低保真原型向目标用户验证理解度和吸引力。",
            triggerProblem: "价值主张是否成立尚未验证",
            coreIdea: "先验证概念理解和价值感，再投入完整实现",
            agentUse: "帮助 Agent 追问用户如何验证别人是否理解并接受这个概念",
            displayText: "概念测试帮助我们判断这个想法是否被目标用户理解和接受。",
            exampleQuestion: "如果只用一句话介绍这个方案，目标用户会因为什么愿意试用？",
            processAction: "验证价值主张",
            cardRole: .content,
            source: "Product discovery method",
            sourceType: "design_method",
            evidenceLevel: .adapted,
            problemTypes: ["concept_unclear", "evaluation_dimensions_missing", "value_too_abstract"],
            relatedFields: [.coreValue, .differentiation, .successMetrics],
            priority: 96,
            uiOutputs: ["methodHint", "processLog"]
        ),
        ResourceCard(
            id: "method-mvp",
            title: "MVP / 最小可行产品",
            type: .method,
            relatedStages: [3, 6, 7, 9],
            tags: ["MVP", "范围", "第一版", "功能", "收敛", "验证"],
            summary: "第一版只保留验证核心价值所必需的最小功能集合。",
            whyRelevant: "当用户想一次做完整产品时，需要先收敛到可验证的第一版。",
            howToUse: "围绕一个核心价值，判断必须做什么、暂时不做什么。",
            triggerProblem: "功能范围过大，不利于第一版验证核心价值",
            coreIdea: "用最小功能验证最关键价值或假设",
            agentUse: "帮助 Agent 推动用户划定 MVP 和排除项",
            displayText: "MVP 帮助我们先保留最能验证核心价值的第一版。",
            exampleQuestion: "如果第一版只验证一个核心价值，最小需要保留哪些功能？",
            processAction: "收敛 MVP 范围",
            cardRole: .content,
            source: "Lean product method",
            sourceType: "design_method",
            evidenceLevel: .adapted,
            problemTypes: ["feature_overload", "scope_expansion", "build_full_product_immediately"],
            relatedFields: [.boundaryItems, .mvpFeatures, .hardConstraints, .milestones],
            priority: 122,
            uiOutputs: ["methodHint", "learningTrace", "processLog"]
        ),
        ResourceCard(
            id: "method-impact-effort-matrix",
            title: "Impact Effort Matrix / 影响-成本矩阵",
            type: .method,
            relatedStages: [3, 6, 9],
            tags: ["优先级", "影响", "成本", "时间", "取舍"],
            summary: "用影响大小和实现成本判断功能优先级，找到高影响、低成本的行动。",
            whyRelevant: "当功能较多或时间有限时，需要结合价值和成本做排序。",
            howToUse: "把候选功能放入影响/成本矩阵，优先选择高影响低成本项。",
            triggerProblem: "候选功能太多，需要结合周期和能力判断优先级",
            coreIdea: "用影响和成本做取舍，而不是按喜欢程度排序",
            agentUse: "帮助 Agent 追问哪些功能最值得先做、哪些应延后",
            displayText: "影响-成本矩阵帮助我们在有限时间里做功能优先级。",
            exampleQuestion: "哪些功能对核心价值影响最大，同时实现成本最低？",
            processAction: "判断功能优先级",
            cardRole: .content,
            source: "Prioritization method",
            sourceType: "design_method",
            evidenceLevel: .adapted,
            problemTypes: ["feature_overload", "time_resource_limit", "schedule_overloaded"],
            relatedFields: [.boundaryItems, .hardConstraints, .milestones],
            priority: 114,
            uiOutputs: ["methodHint", "processLog"]
        ),
        ResourceCard(
            id: "method-decision-log",
            title: "Decision Log / 决策记录",
            type: .method,
            relatedStages: [3, 5, 8, 9],
            tags: ["决策", "依据", "取舍", "记录", "复盘"],
            summary: "记录关键设计取舍、理由和影响，方便后续复盘和汇报。",
            whyRelevant: "当用户完成关键取舍时，需要保存为什么这样决定。",
            howToUse: "记录选择了什么、放弃了什么、依据是什么、影响哪个假设。",
            triggerProblem: "用户已经形成阶段性取舍，需要记录决策依据",
            coreIdea: "把关键取舍变成可追溯的设计证据",
            agentUse: "帮助 Agent 追问用户为什么做出当前选择",
            displayText: "决策记录帮助我们把关键取舍变成可回顾的设计依据。",
            exampleQuestion: "为什么第一阶段选择这些功能？它们分别验证哪个设计假设？",
            processAction: "记录决策依据",
            cardRole: .content,
            source: "Design documentation method",
            sourceType: "design_method",
            evidenceLevel: .adapted,
            problemTypes: ["decision_made", "decision_reason_missing", "stage_completed"],
            relatedFields: [.boundaryItems, .operationLogic, .risks, .milestones],
            priority: 100,
            uiOutputs: ["methodHint", "processLog", "learningTrace"]
        ),
        ResourceCard(
            id: "method-prototype",
            title: "Prototype / 原型",
            type: .method,
            relatedStages: [4],
            tags: ["原型", "功能", "验证", "交互", "低保真"],
            summary: "原型用于学习和验证关键问题，不等于最终产品的小号版本。",
            whyRelevant: "当方案停留在抽象描述时，需要用原型思维拆成可测试材料。",
            howToUse: "先明确原型要回答的问题，再选择纸面、流程图或交互稿。",
            triggerProblem: "方案还停留在抽象描述，缺少可验证形态",
            coreIdea: "用低成本材料验证关键交互或价值假设",
            agentUse: "帮助 Agent 追问应该先做什么低成本原型来验证",
            displayText: "原型帮助我们先验证关键问题，而不是直接做完整产品。",
            exampleQuestion: "这个原型最需要验证哪一个关键问题？",
            processAction: "明确原型目标",
            cardRole: .content,
            source: "Design prototyping method",
            sourceType: "design_method",
            evidenceLevel: .adapted,
            problemTypes: ["prototype_goal_missing", "feature_not_decomposed"],
            relatedFields: [.mvpFeatures, .interactionFlow],
            priority: 104,
            uiOutputs: ["methodHint", "processLog"]
        ),
        ResourceCard(
            id: "method-service-blueprint",
            title: "Service Blueprint / 服务蓝图",
            type: .method,
            relatedStages: [4, 5],
            tags: ["服务蓝图", "前台", "后台", "规则", "流程"],
            summary: "把用户可见流程、系统后台动作和支持流程放在同一张图里检查断点。",
            whyRelevant: "当前后台规则和前台体验之间如果不清楚，系统运行逻辑会断裂。",
            howToUse: "区分用户动作、界面反馈、后台判断和异常支持。",
            triggerProblem: "前台体验和后台规则之间存在断点",
            coreIdea: "同时看见用户行为、系统响应和支持流程",
            agentUse: "帮助 Agent 追问系统在每一步背后如何判断和响应",
            displayText: "服务蓝图帮助我们连接用户看到的流程和系统背后的规则。",
            exampleQuestion: "用户完成这一步时，系统后台需要做出什么判断？",
            processAction: "连接前后台流程",
            cardRole: .content,
            source: "Service design method",
            sourceType: "design_method",
            evidenceLevel: .adapted,
            problemTypes: ["operation_logic_missing", "feedback_missing", "system_status_unclear"],
            relatedFields: [.interactionFlow, .operationLogic],
            priority: 108,
            uiOutputs: ["methodHint", "processLog"]
        ),
        ResourceCard(
            id: "method-crazy-8s",
            title: "Crazy 8s / 八格速想",
            type: .method,
            relatedStages: [4],
            tags: ["发散", "方案", "创意", "功能", "替代方案"],
            summary: "在短时间内快速生成多个不同方案，避免过早锁定单一路径。",
            whyRelevant: "当方案过于单一时，可以先发散多个交互或功能替代方案。",
            howToUse: "围绕同一任务快速列出 4-8 个不同实现方式，再筛选。",
            triggerProblem: "方案过于单一，缺少替代路径",
            coreIdea: "短时间发散多个方向，之后再收敛",
            agentUse: "帮助 Agent 提醒用户考虑不同交互或功能路径",
            displayText: "Crazy 8s 帮助我们先看到多个可能方案，再做取舍。",
            exampleQuestion: "除了当前方案，还有哪两种完全不同的完成方式？",
            processAction: "发散替代方案",
            cardRole: .content,
            source: "Design sprint method",
            sourceType: "design_method",
            evidenceLevel: .adapted,
            problemTypes: ["single_solution", "alternative_missing"],
            relatedFields: [.mvpFeatures, .interactionFlow],
            priority: 82,
            uiOutputs: ["methodHint", "processLog"]
        ),
        ResourceCard(
            id: "method-design-critique",
            title: "Design Critique / 设计评审",
            type: .method,
            relatedStages: [4],
            tags: ["评审", "反馈", "方案", "可用性", "改进"],
            summary: "围绕目标、证据和评价标准检查方案是否服务当前设计意图。",
            whyRelevant: "当功能已经成形但不知道如何改进时，需要有标准地评审。",
            howToUse: "用目标、用户任务、可用性和风险四个角度检查方案。",
            triggerProblem: "方案需要被有标准地检查和改进",
            coreIdea: "评价方案是否服务目标，而不是只凭偏好判断",
            agentUse: "帮助 Agent 追问方案如何被评价、哪里可能不服务目标",
            displayText: "设计评审帮助我们用标准看方案，而不是只看喜不喜欢。",
            exampleQuestion: "这个流程中哪一步最可能不服务当前用户目标？",
            processAction: "检查方案质量",
            cardRole: .content,
            source: "Design critique method",
            sourceType: "design_method",
            evidenceLevel: .adapted,
            problemTypes: ["evaluation_dimensions_missing", "interaction_result_unclear"],
            relatedFields: [.interactionFlow, .successMetrics],
            priority: 80,
            uiOutputs: ["methodHint", "processLog"]
        ),
        ResourceCard(
            id: "method-pre-mortem",
            title: "Pre-mortem / 预先验尸",
            type: .method,
            relatedStages: [5, 6, 8],
            tags: ["风险", "失败", "异常", "预案", "约束"],
            summary: "假设项目已经失败，反推最可能导致失败的原因和预案。",
            whyRelevant: "当用户只描述理想流程或过度乐观时，需要提前暴露失败点。",
            howToUse: "问“如果这个方案失败，最可能失败在哪里”，再设计缓解策略。",
            triggerProblem: "当前规则只覆盖理想情况，没有考虑异常或失败",
            coreIdea: "先假设失败，再反推风险和预案",
            agentUse: "帮助 Agent 追问异常情况、失败原因和恢复路径",
            displayText: "Pre-mortem 帮助我们在失败发生前先看见它。",
            exampleQuestion: "如果这个方案失败，最可能失败在哪里？",
            processAction: "预判失败风险",
            cardRole: .content,
            source: "Risk planning method",
            sourceType: "design_method",
            evidenceLevel: .adapted,
            problemTypes: ["error_flow_missing", "risk_missing", "constraint_ignored", "overtrust_risk"],
            relatedFields: [.operationLogic, .hardConstraints, .risks],
            priority: 116,
            uiOutputs: ["methodHint", "learningTrace", "processLog"]
        ),
        ResourceCard(
            id: "method-experiment-plan",
            title: "Experiment Plan / 实验计划",
            type: .method,
            relatedStages: [7],
            tags: ["实验", "指标", "验收", "测试", "数据"],
            summary: "把“是否有效”转化为可观察指标、测试对象、测试方式和判断标准。",
            whyRelevant: "当用户只说希望有效或喜欢时，需要转化成可衡量标准。",
            howToUse: "定义测试谁、观察什么、成功阈值是什么，以及如何收集数据。",
            triggerProblem: "成功标准过于抽象，无法判断方案是否有效",
            coreIdea: "用可观察指标验证方案是否达成目标",
            agentUse: "帮助 Agent 追问什么数据能证明项目有效",
            displayText: "实验计划帮助我们把“有效”变成可验证的指标。",
            exampleQuestion: "什么数据可以证明用户真的获得了改善？",
            processAction: "制定验证指标",
            cardRole: .content,
            source: "Experiment design method",
            sourceType: "design_method",
            evidenceLevel: .adapted,
            problemTypes: ["metric_not_linked_to_change", "evaluation_dimensions_missing"],
            relatedFields: [.successMetrics],
            priority: 120,
            uiOutputs: ["methodHint", "learningTrace", "processLog"]
        ),
        ResourceCard(
            id: "method-usability-testing",
            title: "Usability Testing / 可用性测试",
            type: .method,
            relatedStages: [7],
            tags: ["可用性", "测试", "任务", "指标", "错误"],
            summary: "通过任务完成情况、错误、时长和理解度判断用户是否能顺利使用方案。",
            whyRelevant: "当验收标准涉及界面或交互时，需要补充可用性指标。",
            howToUse: "设计 1-3 个关键任务，观察完成率、卡顿点、错误和用户理解。",
            triggerProblem: "需要验证用户是否真的会用",
            coreIdea: "用任务表现衡量交互是否可用",
            agentUse: "帮助 Agent 将体验目标转化成可用性测试指标",
            displayText: "可用性测试帮助我们判断用户是否真的能完成任务。",
            exampleQuestion: "用户完成这个关键任务时，哪些行为能证明流程是可用的？",
            processAction: "定义可用性指标",
            cardRole: .content,
            source: "UX research method",
            sourceType: "design_method",
            evidenceLevel: .adapted,
            problemTypes: ["success_metric_missing", "interaction_result_unclear"],
            relatedFields: [.successMetrics, .interactionFlow],
            priority: 100,
            uiOutputs: ["methodHint", "processLog"]
        ),
        ResourceCard(
            id: "method-reflection",
            title: "Reflection / 反思",
            type: .method,
            relatedStages: [9],
            tags: ["反思", "学习", "过程", "复盘", "作品集"],
            summary: "回看关键判断如何形成、依据是什么、还有哪些不确定。",
            whyRelevant: "项目末尾需要把对话过程转化成可展示的设计学习轨迹。",
            howToUse: "总结关键判断、证据、变化和下一步修正方向。",
            triggerProblem: "需要总结学习过程和关键判断",
            coreIdea: "把过程经验转化为可复用的设计能力",
            agentUse: "帮助 Agent 追问用户从项目推进中学到了什么",
            displayText: "反思帮助我们把过程中的判断变化变成学习证据。",
            exampleQuestion: "回看这个项目，哪个判断变化最影响最终方案？",
            processAction: "总结学习过程",
            cardRole: .stageReflection,
            source: "Reflective practice method",
            sourceType: "design_method",
            evidenceLevel: .adapted,
            problemTypes: ["reflection_missing", "project_summary_requested"],
            relatedFields: [.milestones],
            priority: 96,
            uiOutputs: ["methodHint", "learningTrace", "processLog"]
        ),
        ResourceCard(
            id: "method-retrospective",
            title: "Retrospective / 回顾复盘",
            type: .method,
            relatedStages: [9],
            tags: ["复盘", "迭代", "计划", "阶段", "改进"],
            summary: "回顾做得好的地方、卡住的地方和下一轮要调整的策略。",
            whyRelevant: "当项目进入排期或总结时，需要把过程转化为下一轮行动。",
            howToUse: "回答继续保持什么、停止什么、下一步尝试什么。",
            triggerProblem: "需要复盘项目推进方式并调整策略",
            coreIdea: "用回顾推动下一轮改进",
            agentUse: "帮助 Agent 将阶段总结转成下一步计划",
            displayText: "Retrospective 帮助我们从完成情况里找到下一轮改进策略。",
            exampleQuestion: "下一轮推进中，你会继续保持什么、停止什么、尝试什么？",
            processAction: "复盘推进策略",
            cardRole: .selfRegulation,
            source: "Retrospective method",
            sourceType: "design_method",
            evidenceLevel: .adapted,
            problemTypes: ["strategy_needs_adjustment", "project_summary_requested"],
            relatedFields: [.milestones],
            priority: 90,
            uiOutputs: ["methodHint", "learningTrace", "processLog"]
        ),
    ]

    static let theoryCards: [ResourceCard] = [
        ResourceCard(
            id: "T01-wicked-problem-reframing",
            title: "Wicked Problems / 问题会在解决中被重构",
            type: .paper,
            relatedStages: [1, 3, 8],
            tags: ["模糊问题", "复杂性", "问题定义", "重构", "痛点", "边界", "风险"],
            summary: "复杂设计问题通常不会一开始就被完整定义，需要随着用户、场景和约束逐步修正。",
            whyRelevant: "当项目先给出功能或问题过宽时，系统应先帮助用户回到真实用户和具体场景。",
            howToUse: "用于提醒 Agent 追问：这个方案试图解决谁、在什么场景下、遇到的什么困难。",
            year: 1973,
            venue: "Policy Sciences",
            cardRole: .content,
            source: "Rittel & Webber, Dilemmas in a General Theory of Planning",
            sourceType: "peer_reviewed_article",
            evidenceLevel: .direct,
            problemTypes: ["solution_first", "problem_too_broad", "problem_definition_unstable", "problem_reframed"],
            relatedFields: [.targetUser, .painPoint, .useScenario, .boundaryItems],
            priority: 92,
            uiOutputs: ["reflectionCard", "designRationale"],
            triggerSignals: ["用户先说功能清单", "缺少目标用户或场景", "新证据与原问题定义冲突"],
            avoidWhen: ["问题定义已经清晰", "用户正在进行具体实现"]
        ),
        ResourceCard(
            id: "T02-multidimensional-evaluation",
            title: "Wicked Problems / 多维评价而非单一对错",
            type: .paper,
            relatedStages: [2, 7, 8],
            tags: ["评价", "标准", "价值", "风险", "指标", "对错"],
            summary: "开放式方案更适合从价值、适配度、可行性、成本和风险等维度评价。",
            whyRelevant: "当用户只问方案对不对，或验收标准很模糊时，需要建立多个判断维度。",
            howToUse: "推动用户说明：除了功能完成，还要从哪些用户结果和风险维度判断成功。",
            year: 1973,
            venue: "Policy Sciences",
            cardRole: .content,
            source: "Rittel & Webber, Dilemmas in a General Theory of Planning",
            sourceType: "peer_reviewed_article",
            evidenceLevel: .direct,
            problemTypes: ["asks_if_solution_is_correct", "evaluation_dimensions_missing", "binary_judgment"],
            relatedFields: [.coreValue, .differentiation, .successMetrics, .risks],
            priority: 82,
            uiOutputs: ["designRationale", "fieldUpdate"],
            triggerSignals: ["用户问方案是否正确", "只有单一评价指标", "评价标准缺失"]
        ),
        ResourceCard(
            id: "T03-low-cost-validation",
            title: "Wicked Problems / 低成本、可修正的验证",
            type: .paper,
            relatedStages: [4, 8, 9],
            tags: ["验证", "原型", "风险", "成本", "MVP", "里程碑"],
            summary: "原型和测试会消耗资源，也可能改变后续条件；优先选择小范围、低成本、可修正的验证。",
            whyRelevant: "当用户想直接做完整产品时，系统应帮助他们先验证关键假设。",
            howToUse: "将完整开发拆成一个可逆的小测试：验证什么、用什么材料、如何判断结果。",
            year: 1973,
            venue: "Policy Sciences",
            cardRole: .content,
            source: "Rittel & Webber, Dilemmas in a General Theory of Planning",
            sourceType: "peer_reviewed_article",
            evidenceLevel: .adapted,
            problemTypes: ["build_full_product_immediately", "high_cost_validation", "prototype_goal_missing"],
            relatedFields: [.mvpFeatures, .technicalModules, .risks, .milestones],
            priority: 78,
            uiOutputs: ["designNudge", "riskCard"],
            triggerSignals: ["直接开发完整功能", "未说明验证目标", "忽视试错成本"]
        ),
        ResourceCard(
            id: "T04-problem-setting",
            title: "Schon / Problem Setting 先于 Problem Solving",
            type: .paper,
            relatedStages: [1, 3],
            tags: ["问题框定", "主题", "方案", "边界", "开始"],
            summary: "设计前期的重要能力，是把混乱情境框定成值得解决、可以推进的问题。",
            whyRelevant: "当用户只有大主题或直接给方案时，系统需要帮助形成清晰的问题边界。",
            howToUse: "把方向改写成：谁在什么条件下遇到什么困难，需要怎样的改善。",
            year: 1983,
            venue: "The Reflective Practitioner",
            cardRole: .content,
            source: "Donald A. Schon, The Reflective Practitioner",
            sourceType: "book",
            evidenceLevel: .direct,
            problemTypes: ["topic_not_problem", "only_general_direction", "solution_without_problem", "scope_conflicts_with_problem"],
            relatedFields: [.targetUser, .painPoint, .useScenario, .boundaryItems],
            priority: 94,
            uiOutputs: ["problemStatementCard", "reflectionCard"],
            triggerSignals: ["只有主题没有问题", "用户不知道从哪里开始", "功能范围偏离问题"]
        ),
        ResourceCard(
            id: "T05-reflection-in-action",
            title: "Schon / Reflection-in-action",
            type: .paper,
            relatedStages: [1, 2, 3, 4, 5, 6, 7, 8, 9],
            tags: ["反思", "修正", "学习轨迹", "矛盾", "新理解"],
            summary: "实践者会在行动中发现异常、重新理解情境，并即时调整判断。",
            whyRelevant: "当用户修改旧判断时，系统应把它识别为学习轨迹，而不是简单视为前后不一致。",
            howToUse: "比较本轮回答和已有字段，若含义发生变化，提示用户说明新证据或新理解。",
            year: 1983,
            venue: "The Reflective Practitioner",
            cardRole: .reflectionDetector,
            source: "Donald A. Schon, The Reflective Practitioner",
            sourceType: "book",
            evidenceLevel: .direct,
            problemTypes: ["answer_revised", "contradiction_detected", "assumption_changed", "new_understanding"],
            priority: 74,
            uiOutputs: ["reflectionCard", "learningTrace"],
            triggerSignals: ["用户改口且改变原有含义", "用户发现前后矛盾", "新信息推翻旧假设"]
        ),
        ResourceCard(
            id: "T06-reflection-on-action",
            title: "Schon / 阶段结束后的回看",
            type: .paper,
            relatedStages: [1, 2, 3, 4, 5, 6, 7, 8, 9],
            tags: ["复盘", "阶段完成", "总结", "不确定性", "学习轨迹"],
            summary: "阶段结束后的回看帮助学习者理解自己的判断依据、不确定性和下一步修正方向。",
            whyRelevant: "当阶段完成或准备切换时，系统应生成轻量复盘，而不是继续堆叠问题。",
            howToUse: "组织成三句话：关键判断、依据是什么、仍有什么不确定。",
            year: 1983,
            venue: "The Reflective Practitioner",
            cardRole: .stageReflection,
            source: "Donald A. Schon, The Reflective Practitioner",
            sourceType: "book",
            evidenceLevel: .direct,
            problemTypes: ["stage_completed", "before_stage_transition", "project_summary_requested"],
            priority: 72,
            uiOutputs: ["stageSummaryCard", "reflectionCard", "learningTrace"],
            triggerSignals: ["阶段完成度达到阈值", "准备进入下一阶段", "用户主动请求总结"]
        ),
        ResourceCard(
            id: "T07-state-change-value",
            title: "Simon / 设计让现状转向更理想状态",
            type: .paper,
            relatedStages: [1, 2, 7],
            tags: ["价值", "状态变化", "成功指标", "结果", "痛点"],
            summary: "设计价值应体现用户从当前状态转向更理想状态，而不只是功能更多。",
            whyRelevant: "当价值表述停留在“更方便”“更智能”时，系统需要追问用户结果变化。",
            howToUse: "要求用户描述：用户现在是什么状态，成功后会变成什么状态，怎样观察到。",
            year: 1969,
            venue: "The Sciences of the Artificial",
            cardRole: .content,
            source: "Herbert A. Simon, The Sciences of the Artificial",
            sourceType: "book",
            evidenceLevel: .direct,
            problemTypes: ["pain_without_desired_change", "feature_without_user_outcome", "value_too_abstract", "metric_not_linked_to_change"],
            relatedFields: [.painPoint, .coreValue, .successMetrics],
            priority: 86,
            uiOutputs: ["valueCard", "successMetricCard"],
            triggerSignals: ["只写功能不写改变", "价值描述抽象", "验收指标与用户结果无关"]
        ),
        ResourceCard(
            id: "T08-bounded-rationality",
            title: "Simon / Bounded Rationality 与 Satisficing",
            type: .paper,
            relatedStages: [3, 6, 9],
            tags: ["取舍", "范围", "约束", "排期", "优先级", "MVP"],
            summary: "人在有限信息、时间和能力下做决策；早期应寻找足以支撑目标的可行方案。",
            whyRelevant: "当功能膨胀或排期过载时，系统应帮助用户收敛到可落地版本。",
            howToUse: "追问第一版必须保留什么、必须放弃什么，以及哪个约束最不能突破。",
            year: 1955,
            venue: "Behavioral Model of Rational Choice",
            cardRole: .content,
            source: "Herbert A. Simon, Bounded Rationality / Satisficing",
            sourceType: "peer_reviewed_articles",
            evidenceLevel: .direct,
            problemTypes: ["feature_overload", "scope_expansion", "perfect_solution_seeking", "time_resource_limit", "schedule_overloaded"],
            relatedFields: [.boundaryItems, .mvpFeatures, .hardConstraints, .milestones],
            priority: 90,
            uiOutputs: ["scopeCard", "constraintCard", "priorityCard"],
            triggerSignals: ["功能膨胀", "拒绝设置排除项", "时间预算有限", "排期过载"],
            avoidWhen: ["早期创意发散", "用户尚未产生足够选项"]
        ),
        ResourceCard(
            id: "T09-means-ends-analysis",
            title: "Newell & Simon / Means-Ends Analysis",
            type: .paper,
            relatedStages: [4, 6, 9],
            tags: ["下一步", "拆解", "差距", "行动", "里程碑", "模块"],
            summary: "比较当前状态与目标状态的差距，再寻找能缩小差距的行动和子目标。",
            whyRelevant: "当用户不知道下一步或任务太大时，系统应把目标拆成可执行行动。",
            howToUse: "让用户回答：现在在哪里、离目标差什么、下一步最小行动是什么。",
            year: 1972,
            venue: "Human Problem Solving",
            cardRole: .content,
            source: "Newell & Simon, Human Problem Solving",
            sourceType: "book",
            evidenceLevel: .direct,
            problemTypes: ["next_step_unclear", "goal_action_gap", "task_too_large", "feature_not_decomposed"],
            relatedFields: [.technicalModules, .interactionFlow, .hardConstraints, .milestones],
            priority: 84,
            uiOutputs: ["actionPlanCard", "milestoneCard"],
            triggerSignals: ["用户不知道下一步", "任务不可执行", "里程碑过大"]
        ),
        ResourceCard(
            id: "T10-system-feedback",
            title: "Norman / 系统应可发现、可理解、可反馈",
            type: .designPrinciple,
            relatedStages: [4, 5, 7],
            tags: ["交互", "反馈", "状态", "流程", "可用性", "理解"],
            summary: "好的交互让用户知道可以做什么、刚刚做了什么、系统发生了什么。",
            whyRelevant: "当流程缺少入口、状态和操作结果时，系统应引导用户补充反馈机制。",
            howToUse: "检查核心流程每一步：入口是否可见，操作后是否有反馈，用户是否知道结果。",
            year: 2013,
            venue: "The Design of Everyday Things",
            cardRole: .content,
            source: "Donald Norman, The Design of Everyday Things",
            sourceType: "book",
            evidenceLevel: .direct,
            problemTypes: ["feedback_missing", "system_status_unclear", "action_result_invisible", "interaction_result_unclear"],
            relatedFields: [.interactionFlow, .operationLogic, .successMetrics],
            priority: 80,
            uiOutputs: ["interactionFeedbackCard", "designRationale"],
            triggerSignals: ["流程缺少反馈", "状态不清", "操作后没有结果提示"]
        ),
        ResourceCard(
            id: "T12-error-recovery",
            title: "Norman / 错误恢复与可撤销",
            type: .designPrinciple,
            relatedStages: [5, 8],
            tags: ["错误", "恢复", "撤销", "风险", "异常", "规则"],
            summary: "用户和系统都会犯错，好的体验需要让错误可发现、可解释、可恢复。",
            whyRelevant: "当项目没有异常路径或只描述理想流程时，需要补充失败处理。",
            howToUse: "为一个关键错误写出：如何发现、如何提示、用户如何撤销或继续。",
            year: 2013,
            venue: "The Design of Everyday Things",
            cardRole: .content,
            source: "Donald Norman, The Design of Everyday Things",
            sourceType: "book",
            evidenceLevel: .adapted,
            problemTypes: ["error_flow_missing", "undo_missing", "mistake_recovery_missing"],
            relatedFields: [.operationLogic, .risks],
            priority: 82,
            uiOutputs: ["riskCard", "operationRuleCard"],
            triggerSignals: ["没有异常流程", "没有撤销路径", "风险预案缺失"]
        ),
        ResourceCard(
            id: "T14-empathize",
            title: "Stanford d.school / Empathize",
            type: .method,
            relatedStages: [1],
            tags: ["用户", "场景", "共情", "痛点", "目标用户", "访谈"],
            summary: "先理解具体用户在真实情境中的行为、目标和困难，再判断设计机会。",
            whyRelevant: "阶段 1 最需要避免“用户太宽泛”和“场景缺失”。",
            howToUse: "追问一个真实片段：谁、什么时候、在哪里、正在做什么、哪里不顺。",
            venue: "Design Thinking Bootleg",
            cardRole: .content,
            source: "Stanford d.school, Design Thinking Bootleg",
            sourceType: "official_method_guide",
            evidenceLevel: .adapted,
            problemTypes: ["user_too_broad", "scenario_missing", "pain_point_missing"],
            relatedFields: [.targetUser, .useScenario, .painPoint],
            priority: 100,
            uiOutputs: ["fieldUpdate", "reflectionCard", "designRationale"],
            triggerSignals: ["用户对象过宽", "没有具体使用场景", "只有产品想法"]
        ),
        ResourceCard(
            id: "T16-prototyping-purpose",
            title: "Stanford d.school / Prototype to Learn",
            type: .method,
            relatedStages: [4, 7, 9],
            tags: ["原型", "验证", "学习", "展示", "迭代"],
            summary: "原型不是最终产品的小号版本，而是为了学习和验证关键问题的材料。",
            whyRelevant: "当用户过早追求高保真原型时，系统需要拉回验证目标。",
            howToUse: "先写出原型要回答的一个问题，再决定做纸面、交互稿还是功能 demo。",
            venue: "Design Thinking Bootleg",
            cardRole: .content,
            source: "Stanford d.school, Design Thinking Bootleg",
            sourceType: "official_method_guide",
            evidenceLevel: .adapted,
            problemTypes: ["prototype_goal_missing", "high_fidelity_too_early", "prototype_as_final_product"],
            relatedFields: [.mvpFeatures, .successMetrics, .milestones],
            priority: 80,
            uiOutputs: ["prototypeNudge", "milestoneCard"],
            triggerSignals: ["原型目标缺失", "过早高保真", "展示任务不清"]
        ),
        ResourceCard(
            id: "T17-ai-value-fit",
            title: "Google PAIR / AI 应服务真实用户价值",
            type: .caseStudy,
            relatedStages: [2, 3, 4],
            tags: ["AI", "人机协作", "价值", "边界", "自动化"],
            summary: "AI 不应只是卖点，而要说明它在何处比非 AI 方式更适合当前用户任务。",
            whyRelevant: "当项目把 AI 当成标签时，系统需要追问 AI 介入的必要性和边界。",
            howToUse: "检查：AI 何时介入、解决什么判断、用户如何保留控制权。",
            venue: "People + AI Guidebook",
            cardRole: .content,
            source: "Google PAIR, People + AI Guidebook",
            sourceType: "official_method_guide",
            evidenceLevel: .adapted,
            problemTypes: ["ai_value_unclear", "ai_as_selling_point", "technology_without_user_need"],
            relatedFields: [.coreValue, .boundaryItems, .technicalModules],
            requiredContext: ["project_uses_ai"],
            priority: 88,
            uiOutputs: ["designRationale", "scopeCard"],
            triggerSignals: ["项目以 AI 为主要卖点", "AI 不解决明确用户任务", "自动化边界不清"]
        ),
        ResourceCard(
            id: "T18-human-ai-guidelines",
            title: "Human-AI Interaction Guidelines / 置信度与用户控制",
            type: .paper,
            relatedStages: [4, 5, 8],
            tags: ["AI", "置信度", "用户控制", "解释", "错误", "风险"],
            summary: "人机协作系统需要让用户理解 AI 结果的不确定性，并保留确认、纠错和恢复路径。",
            whyRelevant: "当 AI 输出被当作事实或没有纠错机制时，风险会被低估。",
            howToUse: "为 AI 结果设计三件事：说明依据、显示不确定性、允许用户修改或拒绝。",
            year: 2019,
            venue: "CHI",
            cardRole: .content,
            source: "Amershi et al., Guidelines for Human-AI Interaction",
            sourceType: "peer_reviewed_article",
            evidenceLevel: .direct,
            problemTypes: ["ai_output_as_fact", "confidence_not_shown", "overtrust_risk", "user_control_missing"],
            relatedFields: [.interactionFlow, .operationLogic, .risks],
            requiredContext: ["project_uses_ai"],
            priority: 86,
            uiOutputs: ["riskCard", "interactionFeedbackCard"],
            triggerSignals: ["AI 输出没有置信度", "用户不能纠错", "失败路径不清"]
        ),
        ResourceCard(
            id: "T20-agent-role-boundary",
            title: "CoDesign Agent / Agent 角色边界",
            type: .courseFramework,
            relatedStages: [1],
            tags: ["首次使用", "角色", "边界", "助教", "不代做"],
            summary: "Agent 是澄清伙伴，不直接替用户完成关键设计判断。",
            whyRelevant: "首次进入项目或用户要求直接生成完整方案时，需要说明协作方式。",
            howToUse: "用轻量提示说明：我会追问、整理和反馈，但关键取舍仍由你确认。",
            cardRole: .onboarding,
            source: "CoDesign Agent runtime policy",
            sourceType: "internal_design_rule",
            evidenceLevel: .heuristic,
            problemTypes: ["first_interaction", "asks_agent_to_finish_solution"],
            priority: 70,
            applicationScope: ["codesign_app"],
            uiOutputs: ["onboardingCard", "roleBoundaryHint"],
            triggerSignals: ["首次创建项目", "首次进入对话", "用户要求 AI 直接完成方案"]
        ),
        ResourceCard(
            id: "T23-bloom-cognitive-depth",
            title: "Bloom / 问题深度分层",
            type: .courseFramework,
            relatedStages: [1, 2, 3, 4, 5, 6, 7, 8, 9],
            tags: ["认知深度", "理解", "分析", "评价", "浅回答"],
            summary: "问题可以从理解、应用、分析到评价逐步加深，避免一开始就要求过高判断。",
            whyRelevant: "当用户回答太浅或跳不到高阶判断时，系统需要调整问题深度。",
            howToUse: "先问理解型问题，回答稳定后再转向比较、取舍和评价。",
            year: 1956,
            venue: "Taxonomy of Educational Objectives",
            cardRole: .cognitiveDepth,
            source: "Bloom et al.; Anderson & Krathwohl",
            sourceType: "education_framework",
            evidenceLevel: .adapted,
            problemTypes: ["answer_too_shallow", "reasoning_too_shallow"],
            priority: 60,
            applicationScope: ["codesign_app"],
            uiOutputs: ["questionPlan"]
        ),
        ResourceCard(
            id: "T24-socratic-questioning",
            title: "Socratic Questioning / 澄清、证据与假设追问",
            type: .courseFramework,
            relatedStages: [1, 2, 3, 4, 5, 6, 7, 8, 9],
            tags: ["苏格拉底", "追问", "证据", "假设", "澄清"],
            summary: "通过澄清概念、追问证据、暴露假设和比较后果，帮助用户自己形成判断。",
            whyRelevant: "所有阶段都需要保持“引导判断”而不是直接替用户给答案。",
            howToUse: "每轮只选择一种追问方式，并确保问题能推动至少一个缺失字段。",
            venue: "Socratic Questioning in Teaching and Learning",
            cardRole: .questionStrategy,
            source: "Paul & Elder; Elder & Paul",
            sourceType: "education_framework",
            evidenceLevel: .adapted,
            problemTypes: ["claim_without_evidence", "assumption_unchecked", "answer_too_broad"],
            priority: 68,
            applicationScope: ["codesign_app"],
            uiOutputs: ["questionPlan"]
        ),
        ResourceCard(
            id: "T25-adaptive-scaffolding",
            title: "Adaptive Scaffolding / 分级脚手架",
            type: .courseFramework,
            relatedStages: [1, 2, 3, 4, 5, 6, 7, 8, 9],
            tags: ["脚手架", "卡住", "提示", "选项", "例子"],
            summary: "当学习者卡住时，支持应逐步增加：开放问题、结构提示、候选选项、示例模板。",
            whyRelevant: "用户连续不确定时，系统应提供更多结构，但仍不替用户做最终判断。",
            howToUse: "根据卡住程度把问题从开放式改成结构化提示或候选选项。",
            year: 1976,
            venue: "The Role of Tutoring in Problem Solving",
            cardRole: .scaffoldingStrategy,
            source: "Wood, Bruner & Ross, Scaffolding",
            sourceType: "peer_reviewed_article",
            evidenceLevel: .adapted,
            problemTypes: ["user_stuck", "repeated_vague_answer", "asks_for_example"],
            priority: 66,
            applicationScope: ["codesign_app"],
            uiOutputs: ["designNudge", "questionPlan"]
        ),
        ResourceCard(
            id: "T26-cognitive-load-control",
            title: "Cognitive Load / 一次只突出一张主卡",
            type: .courseFramework,
            relatedStages: [1, 2, 3, 4, 5, 6, 7, 8, 9],
            tags: ["认知负荷", "信息量", "折叠", "反馈", "卡片"],
            summary: "界面应控制同时呈现的信息量，主反馈突出，次要更新折叠。",
            whyRelevant: "资源卡和反馈卡过多时，用户会失去当前最重要的下一步。",
            howToUse: "每轮最多显示一张主要资源/反馈卡，其余作为折叠内容或树节点。",
            year: 1988,
            venue: "Cognitive Load During Problem Solving",
            cardRole: .loadControl,
            source: "John Sweller, Cognitive Load Theory",
            sourceType: "peer_reviewed_article",
            evidenceLevel: .adapted,
            problemTypes: ["too_many_cards", "dense_feedback", "ui_overloaded"],
            priority: 64,
            applicationScope: ["codesign_app"],
            uiOutputs: ["collapsedResourceModule", "statusStrip"]
        ),
        ResourceCard(
            id: "T27-formative-feedback",
            title: "Formative Feedback / 目标、进展、下一步",
            type: .courseFramework,
            relatedStages: [1, 2, 3, 4, 5, 6, 7, 8, 9],
            tags: ["反馈", "进展", "下一步", "字段更新", "阶段变化"],
            summary: "有效反馈回答三个问题：目标是什么，当前进展如何，下一步怎么做。",
            whyRelevant: "用户回答后不应只看到“已完成”，而应知道这轮回答推动了什么判断。",
            howToUse: "把反馈组织为：当前目标、本轮进展、下一步追问。",
            year: 2007,
            venue: "Review of Educational Research",
            cardRole: .feedbackStrategy,
            source: "Hattie & Timperley, The Power of Feedback",
            sourceType: "peer_reviewed_article",
            evidenceLevel: .direct,
            problemTypes: ["answer_submitted", "field_updated", "progress_changed"],
            priority: 62,
            applicationScope: ["codesign_app"],
            uiOutputs: ["fieldUpdate", "stageProgressCard", "designNudge"]
        ),
        ResourceCard(
            id: "T28-self-regulated-learning",
            title: "Self-Regulated Learning / 目标、监控与策略调整",
            type: .courseFramework,
            relatedStages: [1, 2, 3, 4, 5, 6, 7, 8, 9],
            tags: ["自我调节", "目标", "监控", "反思", "策略"],
            summary: "学习者需要不断明确目标、监控进展，并根据反馈调整策略。",
            whyRelevant: "阶段、进度、学习轨迹和下一问需要形成闭环，而不是分散显示。",
            howToUse: "阶段完成时提示用户：目标是否改变、证据是否足够、下一步策略是什么。",
            year: 2002,
            venue: "Theory Into Practice",
            cardRole: .selfRegulation,
            source: "Zimmerman, Becoming a Self-Regulated Learner",
            sourceType: "peer_reviewed_article",
            evidenceLevel: .adapted,
            problemTypes: ["goal_missing", "reflection_missing", "strategy_needs_adjustment"],
            priority: 58,
            applicationScope: ["codesign_app"],
            uiOutputs: ["stageSummaryCard", "learningTrace"]
        )
    ]

    static let legacyCards: [ResourceCard] = [
        ResourceCard(
            id: "reflective-practice-schon",
            title: "Reflective Practice / Schon",
            type: .paper,
            relatedStages: [9],
            tags: ["反思", "学习轨迹", "复盘", "过程", "portfolio"],
            summary: "设计师常常在行动中发现问题、修正判断，而不是先得到完整答案。它适合解释设计过程中的反思与迭代。",
            whyRelevant: "你的作品档案需要呈现思考轨迹，而不只是最后方案。",
            howToUse: "在汇报中用它说明：每次重构问题、收敛边界和补充证据，都是设计能力的一部分。"
        ),
        ResourceCard(
            id: "wicked-problems",
            title: "Wicked Problems / Rittel & Webber",
            type: .paper,
            relatedStages: [1, 8],
            tags: ["模糊问题", "复杂性", "风险", "假设", "痛点"],
            summary: "复杂设计问题往往没有一次性正确的定义，需要在讨论与试探中逐步澄清。",
            whyRelevant: "当前阶段需要接受问题的模糊性，并把它转化为可讨论的场景。",
            howToUse: "把你的项目中最模糊的地方写成问题清单，再逐个转成可验证假设。"
        ),
        ResourceCard(
            id: "socratic-questioning",
            title: "Socratic Questioning",
            type: .courseFramework,
            relatedStages: [4],
            tags: ["追问", "概念", "澄清", "为什么", "苏格拉底"],
            summary: "苏格拉底式追问通过连续提问帮助学习者发现隐藏前提，而不是直接给出答案。",
            whyRelevant: "当方案概念还不清晰时，追问能帮助你区分事实、假设和价值判断。",
            howToUse: "针对一个核心概念连续问三次“为什么”和“依据是什么”，记录答案变化。"
        ),
        ResourceCard(
            id: "double-diamond",
            title: "Design Thinking / Double Diamond",
            type: .courseFramework,
            relatedStages: [2, 9],
            tags: ["发散", "收敛", "价值", "流程", "下一步"],
            summary: "Double Diamond 用发散与收敛解释从发现问题到形成方案的过程。",
            whyRelevant: "它能帮助你判断当前是在扩展可能性，还是在收束设计方向。",
            howToUse: "把已有信息放到“发现、定义、发展、交付”四步中，找出下一步缺口。"
        ),
        ResourceCard(
            id: "how-might-we",
            title: "How Might We",
            type: .method,
            relatedStages: [1],
            tags: ["问题陈述", "痛点", "机会点", "场景"],
            summary: "How Might We 把痛点改写成开放但有边界的设计机会。",
            whyRelevant: "阶段 1 需要把模糊抱怨转化为可继续探索的问题。",
            howToUse: "用“我们如何帮助[用户]在[场景]中解决[痛点]”重写项目问题。"
        ),
        ResourceCard(
            id: "persona",
            title: "Persona / 用户画像",
            type: .method,
            relatedStages: [5],
            tags: ["用户", "目标用户", "画像", "需求", "行为"],
            summary: "用户画像用具体角色承载需求、动机、行为和限制，避免设计对象过于泛化。",
            whyRelevant: "如果目标用户还宽泛，画像能让后续功能判断更稳定。",
            howToUse: "写出一个代表性用户的目标、典型场景、阻碍和一句真实口吻的需求。"
        ),
        ResourceCard(
            id: "journey-map",
            title: "User Journey Map",
            type: .method,
            relatedStages: [1, 5],
            tags: ["旅程", "场景", "用户", "触点", "痛点"],
            summary: "用户旅程图按时间线梳理用户行为、触点、情绪和痛点。",
            whyRelevant: "它能把抽象痛点落到具体时刻，帮助你发现关键干预点。",
            howToUse: "列出使用前、使用中、使用后三个阶段，并标出最痛的一个瞬间。"
        ),
        ResourceCard(
            id: "design-criteria",
            title: "Design Criteria / 评价标准",
            type: .method,
            relatedStages: [2, 6],
            tags: ["评价", "指标", "标准", "成功", "验收"],
            summary: "设计评价标准把“好不好”转化为可以观察、比较或验证的判断依据。",
            whyRelevant: "课程汇报需要说明你的方案为什么成立，而不只是看起来合理。",
            howToUse: "写下 3 条评价标准，并说明每条标准如何被观察或测量。"
        ),
        ResourceCard(
            id: "assumption-mapping",
            title: "Assumption Mapping / 假设识别",
            type: .method,
            relatedStages: [3, 8],
            tags: ["假设", "风险", "边界", "可行性", "验证"],
            summary: "假设地图把项目中的未知判断按重要性和不确定性排序。",
            whyRelevant: "边界和风险阶段都需要看清哪些前提还没有证据支撑。",
            howToUse: "列出 5 个关键假设，优先验证“影响大且不确定”的一项。"
        ),
        ResourceCard(
            id: "progressive-disclosure",
            title: "Progressive Disclosure / 逐级展开",
            type: .designPrinciple,
            relatedStages: [4],
            tags: ["交互", "复杂度", "功能", "信息架构", "概念"],
            summary: "逐级展开通过分层呈现信息，避免用户一次面对过多复杂选择。",
            whyRelevant: "当功能越来越多时，它能帮助你保护核心体验。",
            howToUse: "把功能分成默认可见、按需展开和高级设置三层。"
        ),
        ResourceCard(
            id: "hicks-law",
            title: "Hick's Law / 希克定律",
            type: .designPrinciple,
            relatedStages: [4, 6],
            tags: ["选择", "决策", "复杂度", "约束", "界面"],
            summary: "选择越多，用户做决定通常越慢，界面需要控制同时出现的选项数量。",
            whyRelevant: "它能提醒你在功能拆解时避免把所有能力都塞进第一版。",
            howToUse: "检查核心流程中每一步的选项数量，删掉不服务当前目标的选择。"
        ),
        ResourceCard(
            id: "gestalt-principles",
            title: "Gestalt Principles / 格式塔原则",
            type: .designPrinciple,
            relatedStages: [4],
            tags: ["视觉", "布局", "分组", "界面", "可读性"],
            summary: "格式塔原则解释人们如何通过接近、相似、连续等线索理解界面结构。",
            whyRelevant: "当你准备原型或展示图时，它能提高信息组织的清晰度。",
            howToUse: "检查同类信息是否靠近、样式是否一致、视觉层级是否能被快速扫读。"
        ),
        ResourceCard(
            id: "feedback-loop",
            title: "Feedback Loop / 反馈循环",
            type: .designPrinciple,
            relatedStages: [6],
            tags: ["反馈", "评价", "指标", "迭代", "验证"],
            summary: "反馈循环让用户行为、系统响应和后续改进形成可观察的闭环。",
            whyRelevant: "评价标准不应只停留在结果，也要说明如何回到下一轮设计。",
            howToUse: "为一个关键指标写出：谁提供反馈、何时收集、如何影响下一次迭代。"
        ),
        ResourceCard(
            id: "google-pair-guidebook",
            title: "Google PAIR Guidebook",
            type: .caseStudy,
            relatedStages: [3, 7],
            tags: ["AI", "人机协作", "边界", "可行性", "责任"],
            summary: "PAIR Guidebook 提供以人为中心设计 AI 产品的方法和问题清单。",
            whyRelevant: "如果项目涉及 AI，必须说明系统边界、用户控制和失败处理。",
            howToUse: "用它检查：AI 何时介入、用户如何理解结果、错误输出如何被处理。"
        ),
        ResourceCard(
            id: "notebooklm-audio-overview",
            title: "NotebookLM Audio Overview",
            type: .caseStudy,
            relatedStages: [7],
            tags: ["AI", "案例", "学习", "音频", "原生体验"],
            summary: "NotebookLM 的音频概览展示了 AI 原生学习体验如何把资料转化为可听、可讨论的内容。",
            whyRelevant: "它能启发你思考 AI 不只是生成文本，也可以改变学习材料的呈现方式。",
            howToUse: "分析它把哪些学习动作自动化、哪些判断仍留给用户。"
        ),
        ResourceCard(
            id: "ai-behavior-designer",
            title: "Course Assistant / AI Behavior Designer Framework",
            type: .courseFramework,
            relatedStages: [7],
            tags: ["AI", "助教", "行为", "可行性", "课程"],
            summary: "AI 行为设计关注系统在何时追问、何时建议、何时保持沉默。",
            whyRelevant: "它适合评估课程助教类项目是否真正支持学习过程，而不是替学生完成任务。",
            howToUse: "为你的 AI 写三条行为规则：应该追问什么、推荐什么、避免代替用户做什么。"
        )
    ]
}
