import Foundation

enum ResourceLibrary {
    static let all: [ResourceCard] = theoryCards + legacyCards

    static let theoryCards: [ResourceCard] = [
        ResourceCard(
            id: "T01-wicked-problem-reframing",
            title: "Wicked Problems / 问题会在解决中被重构",
            type: .paper,
            relatedStages: [1, 3, 8],
            tags: ["模糊问题", "复杂性", "问题定义", "重构", "痛点", "边界", "风险"],
            summary: "复杂设计问题通常不会一开始就被完整定义，需要随着用户、场景和约束逐步修正。",
            whyRelevant: "当项目先给出功能或问题过宽时，系统应先帮助用户回到真实用户和具体场景。",
            howToUse: "用于提醒 Agent 追问：这个方案试图解决谁、在什么场景下、遇到的什么困难。",
            year: 1973,
            venue: "Policy Sciences",
            cardRole: .content,
            source: "Rittel & Webber, Dilemmas in a General Theory of Planning",
            sourceType: "peer_reviewed_article",
            evidenceLevel: .direct,
            problemTypes: ["solution_first", "problem_too_broad", "problem_definition_unstable", "problem_reframed"],
            relatedFields: [.targetUser, .painPoint, .useScenario, .boundaryItems],
            priority: 92,
            uiOutputs: ["reflectionCard", "designRationale"],
            triggerSignals: ["用户先说功能清单", "缺少目标用户或场景", "新证据与原问题定义冲突"],
            avoidWhen: ["问题定义已经清晰", "用户正在进行具体实现"]
        ),
        ResourceCard(
            id: "T02-multidimensional-evaluation",
            title: "Wicked Problems / 多维评价而非单一对错",
            type: .paper,
            relatedStages: [2, 7, 8],
            tags: ["评价", "标准", "价值", "风险", "指标", "对错"],
            summary: "开放式方案更适合从价值、适配度、可行性、成本和风险等维度评价。",
            whyRelevant: "当用户只问方案对不对，或验收标准很模糊时，需要建立多个判断维度。",
            howToUse: "推动用户说明：除了功能完成，还要从哪些用户结果和风险维度判断成功。",
            year: 1973,
            venue: "Policy Sciences",
            cardRole: .content,
            source: "Rittel & Webber, Dilemmas in a General Theory of Planning",
            sourceType: "peer_reviewed_article",
            evidenceLevel: .direct,
            problemTypes: ["asks_if_solution_is_correct", "evaluation_dimensions_missing", "binary_judgment"],
            relatedFields: [.coreValue, .differentiation, .successMetrics, .risks],
            priority: 82,
            uiOutputs: ["designRationale", "fieldUpdate"],
            triggerSignals: ["用户问方案是否正确", "只有单一评价指标", "评价标准缺失"]
        ),
        ResourceCard(
            id: "T03-low-cost-validation",
            title: "Wicked Problems / 低成本、可修正的验证",
            type: .paper,
            relatedStages: [4, 8, 9],
            tags: ["验证", "原型", "风险", "成本", "MVP", "里程碑"],
            summary: "原型和测试会消耗资源，也可能改变后续条件；优先选择小范围、低成本、可修正的验证。",
            whyRelevant: "当用户想直接做完整产品时，系统应帮助他们先验证关键假设。",
            howToUse: "将完整开发拆成一个可逆的小测试：验证什么、用什么材料、如何判断结果。",
            year: 1973,
            venue: "Policy Sciences",
            cardRole: .content,
            source: "Rittel & Webber, Dilemmas in a General Theory of Planning",
            sourceType: "peer_reviewed_article",
            evidenceLevel: .adapted,
            problemTypes: ["build_full_product_immediately", "high_cost_validation", "prototype_goal_missing"],
            relatedFields: [.mvpFeatures, .technicalModules, .risks, .milestones],
            priority: 78,
            uiOutputs: ["designNudge", "riskCard"],
            triggerSignals: ["直接开发完整功能", "未说明验证目标", "忽视试错成本"]
        ),
        ResourceCard(
            id: "T04-problem-setting",
            title: "Schon / Problem Setting 先于 Problem Solving",
            type: .paper,
            relatedStages: [1, 3],
            tags: ["问题框定", "主题", "方案", "边界", "开始"],
            summary: "设计前期的重要能力，是把混乱情境框定成值得解决、可以推进的问题。",
            whyRelevant: "当用户只有大主题或直接给方案时，系统需要帮助形成清晰的问题边界。",
            howToUse: "把方向改写成：谁在什么条件下遇到什么困难，需要怎样的改善。",
            year: 1983,
            venue: "The Reflective Practitioner",
            cardRole: .content,
            source: "Donald A. Schon, The Reflective Practitioner",
            sourceType: "book",
            evidenceLevel: .direct,
            problemTypes: ["topic_not_problem", "only_general_direction", "solution_without_problem", "scope_conflicts_with_problem"],
            relatedFields: [.targetUser, .painPoint, .useScenario, .boundaryItems],
            priority: 94,
            uiOutputs: ["problemStatementCard", "reflectionCard"],
            triggerSignals: ["只有主题没有问题", "用户不知道从哪里开始", "功能范围偏离问题"]
        ),
        ResourceCard(
            id: "T05-reflection-in-action",
            title: "Schon / Reflection-in-action",
            type: .paper,
            relatedStages: [1, 2, 3, 4, 5, 6, 7, 8, 9],
            tags: ["反思", "修正", "学习轨迹", "矛盾", "新理解"],
            summary: "实践者会在行动中发现异常、重新理解情境，并即时调整判断。",
            whyRelevant: "当用户修改旧判断时，系统应把它识别为学习轨迹，而不是简单视为前后不一致。",
            howToUse: "比较本轮回答和已有字段，若含义发生变化，提示用户说明新证据或新理解。",
            year: 1983,
            venue: "The Reflective Practitioner",
            cardRole: .reflectionDetector,
            source: "Donald A. Schon, The Reflective Practitioner",
            sourceType: "book",
            evidenceLevel: .direct,
            problemTypes: ["answer_revised", "contradiction_detected", "assumption_changed", "new_understanding"],
            priority: 74,
            uiOutputs: ["reflectionCard", "learningTrace"],
            triggerSignals: ["用户改口且改变原有含义", "用户发现前后矛盾", "新信息推翻旧假设"]
        ),
        ResourceCard(
            id: "T06-reflection-on-action",
            title: "Schon / 阶段结束后的回看",
            type: .paper,
            relatedStages: [1, 2, 3, 4, 5, 6, 7, 8, 9],
            tags: ["复盘", "阶段完成", "总结", "不确定性", "学习轨迹"],
            summary: "阶段结束后的回看帮助学习者理解自己的判断依据、不确定性和下一步修正方向。",
            whyRelevant: "当阶段完成或准备切换时，系统应生成轻量复盘，而不是继续堆叠问题。",
            howToUse: "组织成三句话：关键判断、依据是什么、仍有什么不确定。",
            year: 1983,
            venue: "The Reflective Practitioner",
            cardRole: .stageReflection,
            source: "Donald A. Schon, The Reflective Practitioner",
            sourceType: "book",
            evidenceLevel: .direct,
            problemTypes: ["stage_completed", "before_stage_transition", "project_summary_requested"],
            priority: 72,
            uiOutputs: ["stageSummaryCard", "reflectionCard", "learningTrace"],
            triggerSignals: ["阶段完成度达到阈值", "准备进入下一阶段", "用户主动请求总结"]
        ),
        ResourceCard(
            id: "T07-state-change-value",
            title: "Simon / 设计让现状转向更理想状态",
            type: .paper,
            relatedStages: [1, 2, 7],
            tags: ["价值", "状态变化", "成功指标", "结果", "痛点"],
            summary: "设计价值应体现用户从当前状态转向更理想状态，而不只是功能更多。",
            whyRelevant: "当价值表述停留在“更方便”“更智能”时，系统需要追问用户结果变化。",
            howToUse: "要求用户描述：用户现在是什么状态，成功后会变成什么状态，怎样观察到。",
            year: 1969,
            venue: "The Sciences of the Artificial",
            cardRole: .content,
            source: "Herbert A. Simon, The Sciences of the Artificial",
            sourceType: "book",
            evidenceLevel: .direct,
            problemTypes: ["pain_without_desired_change", "feature_without_user_outcome", "value_too_abstract", "metric_not_linked_to_change"],
            relatedFields: [.painPoint, .coreValue, .successMetrics],
            priority: 86,
            uiOutputs: ["valueCard", "successMetricCard"],
            triggerSignals: ["只写功能不写改变", "价值描述抽象", "验收指标与用户结果无关"]
        ),
        ResourceCard(
            id: "T08-bounded-rationality",
            title: "Simon / Bounded Rationality 与 Satisficing",
            type: .paper,
            relatedStages: [3, 6, 9],
            tags: ["取舍", "范围", "约束", "排期", "优先级", "MVP"],
            summary: "人在有限信息、时间和能力下做决策；早期应寻找足以支撑目标的可行方案。",
            whyRelevant: "当功能膨胀或排期过载时，系统应帮助用户收敛到可落地版本。",
            howToUse: "追问第一版必须保留什么、必须放弃什么，以及哪个约束最不能突破。",
            year: 1955,
            venue: "Behavioral Model of Rational Choice",
            cardRole: .content,
            source: "Herbert A. Simon, Bounded Rationality / Satisficing",
            sourceType: "peer_reviewed_articles",
            evidenceLevel: .direct,
            problemTypes: ["feature_overload", "scope_expansion", "perfect_solution_seeking", "time_resource_limit", "schedule_overloaded"],
            relatedFields: [.boundaryItems, .mvpFeatures, .hardConstraints, .milestones],
            priority: 90,
            uiOutputs: ["scopeCard", "constraintCard", "priorityCard"],
            triggerSignals: ["功能膨胀", "拒绝设置排除项", "时间预算有限", "排期过载"],
            avoidWhen: ["早期创意发散", "用户尚未产生足够选项"]
        ),
        ResourceCard(
            id: "T09-means-ends-analysis",
            title: "Newell & Simon / Means-Ends Analysis",
            type: .paper,
            relatedStages: [4, 6, 9],
            tags: ["下一步", "拆解", "差距", "行动", "里程碑", "模块"],
            summary: "比较当前状态与目标状态的差距，再寻找能缩小差距的行动和子目标。",
            whyRelevant: "当用户不知道下一步或任务太大时，系统应把目标拆成可执行行动。",
            howToUse: "让用户回答：现在在哪里、离目标差什么、下一步最小行动是什么。",
            year: 1972,
            venue: "Human Problem Solving",
            cardRole: .content,
            source: "Newell & Simon, Human Problem Solving",
            sourceType: "book",
            evidenceLevel: .direct,
            problemTypes: ["next_step_unclear", "goal_action_gap", "task_too_large", "feature_not_decomposed"],
            relatedFields: [.technicalModules, .interactionFlow, .hardConstraints, .milestones],
            priority: 84,
            uiOutputs: ["actionPlanCard", "milestoneCard"],
            triggerSignals: ["用户不知道下一步", "任务不可执行", "里程碑过大"]
        ),
        ResourceCard(
            id: "T10-system-feedback",
            title: "Norman / 系统应可发现、可理解、可反馈",
            type: .designPrinciple,
            relatedStages: [4, 5, 7],
            tags: ["交互", "反馈", "状态", "流程", "可用性", "理解"],
            summary: "好的交互让用户知道可以做什么、刚刚做了什么、系统发生了什么。",
            whyRelevant: "当流程缺少入口、状态和操作结果时，系统应引导用户补充反馈机制。",
            howToUse: "检查核心流程每一步：入口是否可见，操作后是否有反馈，用户是否知道结果。",
            year: 2013,
            venue: "The Design of Everyday Things",
            cardRole: .content,
            source: "Donald Norman, The Design of Everyday Things",
            sourceType: "book",
            evidenceLevel: .direct,
            problemTypes: ["feedback_missing", "system_status_unclear", "action_result_invisible", "interaction_result_unclear"],
            relatedFields: [.interactionFlow, .operationLogic, .successMetrics],
            priority: 80,
            uiOutputs: ["interactionFeedbackCard", "designRationale"],
            triggerSignals: ["流程缺少反馈", "状态不清", "操作后没有结果提示"]
        ),
        ResourceCard(
            id: "T12-error-recovery",
            title: "Norman / 错误恢复与可撤销",
            type: .designPrinciple,
            relatedStages: [5, 8],
            tags: ["错误", "恢复", "撤销", "风险", "异常", "规则"],
            summary: "用户和系统都会犯错，好的体验需要让错误可发现、可解释、可恢复。",
            whyRelevant: "当项目没有异常路径或只描述理想流程时，需要补充失败处理。",
            howToUse: "为一个关键错误写出：如何发现、如何提示、用户如何撤销或继续。",
            year: 2013,
            venue: "The Design of Everyday Things",
            cardRole: .content,
            source: "Donald Norman, The Design of Everyday Things",
            sourceType: "book",
            evidenceLevel: .adapted,
            problemTypes: ["error_flow_missing", "undo_missing", "mistake_recovery_missing"],
            relatedFields: [.operationLogic, .risks],
            priority: 82,
            uiOutputs: ["riskCard", "operationRuleCard"],
            triggerSignals: ["没有异常流程", "没有撤销路径", "风险预案缺失"]
        ),
        ResourceCard(
            id: "T14-empathize",
            title: "Stanford d.school / Empathize",
            type: .method,
            relatedStages: [1],
            tags: ["用户", "场景", "共情", "痛点", "目标用户", "访谈"],
            summary: "先理解具体用户在真实情境中的行为、目标和困难，再判断设计机会。",
            whyRelevant: "阶段 1 最需要避免“用户太宽泛”和“场景缺失”。",
            howToUse: "追问一个真实片段：谁、什么时候、在哪里、正在做什么、哪里不顺。",
            venue: "Design Thinking Bootleg",
            cardRole: .content,
            source: "Stanford d.school, Design Thinking Bootleg",
            sourceType: "official_method_guide",
            evidenceLevel: .adapted,
            problemTypes: ["user_too_broad", "scenario_missing", "pain_point_missing"],
            relatedFields: [.targetUser, .useScenario, .painPoint],
            priority: 100,
            uiOutputs: ["fieldUpdate", "reflectionCard", "designRationale"],
            triggerSignals: ["用户对象过宽", "没有具体使用场景", "只有产品想法"]
        ),
        ResourceCard(
            id: "T16-prototyping-purpose",
            title: "Stanford d.school / Prototype to Learn",
            type: .method,
            relatedStages: [4, 7, 9],
            tags: ["原型", "验证", "学习", "展示", "迭代"],
            summary: "原型不是最终产品的小号版本，而是为了学习和验证关键问题的材料。",
            whyRelevant: "当用户过早追求高保真原型时，系统需要拉回验证目标。",
            howToUse: "先写出原型要回答的一个问题，再决定做纸面、交互稿还是功能 demo。",
            venue: "Design Thinking Bootleg",
            cardRole: .content,
            source: "Stanford d.school, Design Thinking Bootleg",
            sourceType: "official_method_guide",
            evidenceLevel: .adapted,
            problemTypes: ["prototype_goal_missing", "high_fidelity_too_early", "prototype_as_final_product"],
            relatedFields: [.mvpFeatures, .successMetrics, .milestones],
            priority: 80,
            uiOutputs: ["prototypeNudge", "milestoneCard"],
            triggerSignals: ["原型目标缺失", "过早高保真", "展示任务不清"]
        ),
        ResourceCard(
            id: "T17-ai-value-fit",
            title: "Google PAIR / AI 应服务真实用户价值",
            type: .caseStudy,
            relatedStages: [2, 3, 4],
            tags: ["AI", "人机协作", "价值", "边界", "自动化"],
            summary: "AI 不应只是卖点，而要说明它在何处比非 AI 方式更适合当前用户任务。",
            whyRelevant: "当项目把 AI 当成标签时，系统需要追问 AI 介入的必要性和边界。",
            howToUse: "检查：AI 何时介入、解决什么判断、用户如何保留控制权。",
            venue: "People + AI Guidebook",
            cardRole: .content,
            source: "Google PAIR, People + AI Guidebook",
            sourceType: "official_method_guide",
            evidenceLevel: .adapted,
            problemTypes: ["ai_value_unclear", "ai_as_selling_point", "technology_without_user_need"],
            relatedFields: [.coreValue, .boundaryItems, .technicalModules],
            requiredContext: ["project_uses_ai"],
            priority: 88,
            uiOutputs: ["designRationale", "scopeCard"],
            triggerSignals: ["项目以 AI 为主要卖点", "AI 不解决明确用户任务", "自动化边界不清"]
        ),
        ResourceCard(
            id: "T18-human-ai-guidelines",
            title: "Human-AI Interaction Guidelines / 置信度与用户控制",
            type: .paper,
            relatedStages: [4, 5, 8],
            tags: ["AI", "置信度", "用户控制", "解释", "错误", "风险"],
            summary: "人机协作系统需要让用户理解 AI 结果的不确定性，并保留确认、纠错和恢复路径。",
            whyRelevant: "当 AI 输出被当作事实或没有纠错机制时，风险会被低估。",
            howToUse: "为 AI 结果设计三件事：说明依据、显示不确定性、允许用户修改或拒绝。",
            year: 2019,
            venue: "CHI",
            cardRole: .content,
            source: "Amershi et al., Guidelines for Human-AI Interaction",
            sourceType: "peer_reviewed_article",
            evidenceLevel: .direct,
            problemTypes: ["ai_output_as_fact", "confidence_not_shown", "overtrust_risk", "user_control_missing"],
            relatedFields: [.interactionFlow, .operationLogic, .risks],
            requiredContext: ["project_uses_ai"],
            priority: 86,
            uiOutputs: ["riskCard", "interactionFeedbackCard"],
            triggerSignals: ["AI 输出没有置信度", "用户不能纠错", "失败路径不清"]
        ),
        ResourceCard(
            id: "T20-agent-role-boundary",
            title: "CoDesign Agent / Agent 角色边界",
            type: .courseFramework,
            relatedStages: [1],
            tags: ["首次使用", "角色", "边界", "助教", "不代做"],
            summary: "Agent 是澄清伙伴，不直接替用户完成关键设计判断。",
            whyRelevant: "首次进入项目或用户要求直接生成完整方案时，需要说明协作方式。",
            howToUse: "用轻量提示说明：我会追问、整理和反馈，但关键取舍仍由你确认。",
            cardRole: .onboarding,
            source: "CoDesign Agent runtime policy",
            sourceType: "internal_design_rule",
            evidenceLevel: .heuristic,
            problemTypes: ["first_interaction", "asks_agent_to_finish_solution"],
            priority: 70,
            applicationScope: ["codesign_app"],
            uiOutputs: ["onboardingCard", "roleBoundaryHint"],
            triggerSignals: ["首次创建项目", "首次进入对话", "用户要求 AI 直接完成方案"]
        ),
        ResourceCard(
            id: "T23-bloom-cognitive-depth",
            title: "Bloom / 问题深度分层",
            type: .courseFramework,
            relatedStages: [1, 2, 3, 4, 5, 6, 7, 8, 9],
            tags: ["认知深度", "理解", "分析", "评价", "浅回答"],
            summary: "问题可以从理解、应用、分析到评价逐步加深，避免一开始就要求过高判断。",
            whyRelevant: "当用户回答太浅或跳不到高阶判断时，系统需要调整问题深度。",
            howToUse: "先问理解型问题，回答稳定后再转向比较、取舍和评价。",
            year: 1956,
            venue: "Taxonomy of Educational Objectives",
            cardRole: .cognitiveDepth,
            source: "Bloom et al.; Anderson & Krathwohl",
            sourceType: "education_framework",
            evidenceLevel: .adapted,
            problemTypes: ["answer_too_shallow", "reasoning_too_shallow"],
            priority: 60,
            applicationScope: ["codesign_app"],
            uiOutputs: ["questionPlan"]
        ),
        ResourceCard(
            id: "T24-socratic-questioning",
            title: "Socratic Questioning / 澄清、证据与假设追问",
            type: .courseFramework,
            relatedStages: [1, 2, 3, 4, 5, 6, 7, 8, 9],
            tags: ["苏格拉底", "追问", "证据", "假设", "澄清"],
            summary: "通过澄清概念、追问证据、暴露假设和比较后果，帮助用户自己形成判断。",
            whyRelevant: "所有阶段都需要保持“引导判断”而不是直接替用户给答案。",
            howToUse: "每轮只选择一种追问方式，并确保问题能推动至少一个缺失字段。",
            venue: "Socratic Questioning in Teaching and Learning",
            cardRole: .questionStrategy,
            source: "Paul & Elder; Elder & Paul",
            sourceType: "education_framework",
            evidenceLevel: .adapted,
            problemTypes: ["claim_without_evidence", "assumption_unchecked", "answer_too_broad"],
            priority: 68,
            applicationScope: ["codesign_app"],
            uiOutputs: ["questionPlan"]
        ),
        ResourceCard(
            id: "T25-adaptive-scaffolding",
            title: "Adaptive Scaffolding / 分级脚手架",
            type: .courseFramework,
            relatedStages: [1, 2, 3, 4, 5, 6, 7, 8, 9],
            tags: ["脚手架", "卡住", "提示", "选项", "例子"],
            summary: "当学习者卡住时，支持应逐步增加：开放问题、结构提示、候选选项、示例模板。",
            whyRelevant: "用户连续不确定时，系统应提供更多结构，但仍不替用户做最终判断。",
            howToUse: "根据卡住程度把问题从开放式改成结构化提示或候选选项。",
            year: 1976,
            venue: "The Role of Tutoring in Problem Solving",
            cardRole: .scaffoldingStrategy,
            source: "Wood, Bruner & Ross, Scaffolding",
            sourceType: "peer_reviewed_article",
            evidenceLevel: .adapted,
            problemTypes: ["user_stuck", "repeated_vague_answer", "asks_for_example"],
            priority: 66,
            applicationScope: ["codesign_app"],
            uiOutputs: ["designNudge", "questionPlan"]
        ),
        ResourceCard(
            id: "T26-cognitive-load-control",
            title: "Cognitive Load / 一次只突出一张主卡",
            type: .courseFramework,
            relatedStages: [1, 2, 3, 4, 5, 6, 7, 8, 9],
            tags: ["认知负荷", "信息量", "折叠", "反馈", "卡片"],
            summary: "界面应控制同时呈现的信息量，主反馈突出，次要更新折叠。",
            whyRelevant: "资源卡和反馈卡过多时，用户会失去当前最重要的下一步。",
            howToUse: "每轮最多显示一张主要资源/反馈卡，其余作为折叠内容或树节点。",
            year: 1988,
            venue: "Cognitive Load During Problem Solving",
            cardRole: .loadControl,
            source: "John Sweller, Cognitive Load Theory",
            sourceType: "peer_reviewed_article",
            evidenceLevel: .adapted,
            problemTypes: ["too_many_cards", "dense_feedback", "ui_overloaded"],
            priority: 64,
            applicationScope: ["codesign_app"],
            uiOutputs: ["collapsedResourceModule", "statusStrip"]
        ),
        ResourceCard(
            id: "T27-formative-feedback",
            title: "Formative Feedback / 目标、进展、下一步",
            type: .courseFramework,
            relatedStages: [1, 2, 3, 4, 5, 6, 7, 8, 9],
            tags: ["反馈", "进展", "下一步", "字段更新", "阶段变化"],
            summary: "有效反馈回答三个问题：目标是什么，当前进展如何，下一步怎么做。",
            whyRelevant: "用户回答后不应只看到“已完成”，而应知道这轮回答推动了什么判断。",
            howToUse: "把反馈组织为：当前目标、本轮进展、下一步追问。",
            year: 2007,
            venue: "Review of Educational Research",
            cardRole: .feedbackStrategy,
            source: "Hattie & Timperley, The Power of Feedback",
            sourceType: "peer_reviewed_article",
            evidenceLevel: .direct,
            problemTypes: ["answer_submitted", "field_updated", "progress_changed"],
            priority: 62,
            applicationScope: ["codesign_app"],
            uiOutputs: ["fieldUpdate", "stageProgressCard", "designNudge"]
        ),
        ResourceCard(
            id: "T28-self-regulated-learning",
            title: "Self-Regulated Learning / 目标、监控与策略调整",
            type: .courseFramework,
            relatedStages: [1, 2, 3, 4, 5, 6, 7, 8, 9],
            tags: ["自我调节", "目标", "监控", "反思", "策略"],
            summary: "学习者需要不断明确目标、监控进展，并根据反馈调整策略。",
            whyRelevant: "阶段、进度、学习轨迹和下一问需要形成闭环，而不是分散显示。",
            howToUse: "阶段完成时提示用户：目标是否改变、证据是否足够、下一步策略是什么。",
            year: 2002,
            venue: "Theory Into Practice",
            cardRole: .selfRegulation,
            source: "Zimmerman, Becoming a Self-Regulated Learner",
            sourceType: "peer_reviewed_article",
            evidenceLevel: .adapted,
            problemTypes: ["goal_missing", "reflection_missing", "strategy_needs_adjustment"],
            priority: 58,
            applicationScope: ["codesign_app"],
            uiOutputs: ["stageSummaryCard", "learningTrace"]
        )
    ]

    static let legacyCards: [ResourceCard] = [
        ResourceCard(
            id: "reflective-practice-schon",
            title: "Reflective Practice / Schon",
            type: .paper,
            relatedStages: [9],
            tags: ["反思", "学习轨迹", "复盘", "过程", "portfolio"],
            summary: "设计师常常在行动中发现问题、修正判断，而不是先得到完整答案。它适合解释设计过程中的反思与迭代。",
            whyRelevant: "你的作品档案需要呈现思考轨迹，而不只是最后方案。",
            howToUse: "在汇报中用它说明：每次重构问题、收敛边界和补充证据，都是设计能力的一部分。"
        ),
        ResourceCard(
            id: "wicked-problems",
            title: "Wicked Problems / Rittel & Webber",
            type: .paper,
            relatedStages: [1, 8],
            tags: ["模糊问题", "复杂性", "风险", "假设", "痛点"],
            summary: "复杂设计问题往往没有一次性正确的定义，需要在讨论与试探中逐步澄清。",
            whyRelevant: "当前阶段需要接受问题的模糊性，并把它转化为可讨论的场景。",
            howToUse: "把你的项目中最模糊的地方写成问题清单，再逐个转成可验证假设。"
        ),
        ResourceCard(
            id: "socratic-questioning",
            title: "Socratic Questioning",
            type: .courseFramework,
            relatedStages: [4],
            tags: ["追问", "概念", "澄清", "为什么", "苏格拉底"],
            summary: "苏格拉底式追问通过连续提问帮助学习者发现隐藏前提，而不是直接给出答案。",
            whyRelevant: "当方案概念还不清晰时，追问能帮助你区分事实、假设和价值判断。",
            howToUse: "针对一个核心概念连续问三次“为什么”和“依据是什么”，记录答案变化。"
        ),
        ResourceCard(
            id: "double-diamond",
            title: "Design Thinking / Double Diamond",
            type: .courseFramework,
            relatedStages: [2, 9],
            tags: ["发散", "收敛", "价值", "流程", "下一步"],
            summary: "Double Diamond 用发散与收敛解释从发现问题到形成方案的过程。",
            whyRelevant: "它能帮助你判断当前是在扩展可能性，还是在收束设计方向。",
            howToUse: "把已有信息放到“发现、定义、发展、交付”四步中，找出下一步缺口。"
        ),
        ResourceCard(
            id: "how-might-we",
            title: "How Might We",
            type: .method,
            relatedStages: [1],
            tags: ["问题陈述", "痛点", "机会点", "场景"],
            summary: "How Might We 把痛点改写成开放但有边界的设计机会。",
            whyRelevant: "阶段 1 需要把模糊抱怨转化为可继续探索的问题。",
            howToUse: "用“我们如何帮助[用户]在[场景]中解决[痛点]”重写项目问题。"
        ),
        ResourceCard(
            id: "persona",
            title: "Persona / 用户画像",
            type: .method,
            relatedStages: [5],
            tags: ["用户", "目标用户", "画像", "需求", "行为"],
            summary: "用户画像用具体角色承载需求、动机、行为和限制，避免设计对象过于泛化。",
            whyRelevant: "如果目标用户还宽泛，画像能让后续功能判断更稳定。",
            howToUse: "写出一个代表性用户的目标、典型场景、阻碍和一句真实口吻的需求。"
        ),
        ResourceCard(
            id: "journey-map",
            title: "User Journey Map",
            type: .method,
            relatedStages: [1, 5],
            tags: ["旅程", "场景", "用户", "触点", "痛点"],
            summary: "用户旅程图按时间线梳理用户行为、触点、情绪和痛点。",
            whyRelevant: "它能把抽象痛点落到具体时刻，帮助你发现关键干预点。",
            howToUse: "列出使用前、使用中、使用后三个阶段，并标出最痛的一个瞬间。"
        ),
        ResourceCard(
            id: "design-criteria",
            title: "Design Criteria / 评价标准",
            type: .method,
            relatedStages: [2, 6],
            tags: ["评价", "指标", "标准", "成功", "验收"],
            summary: "设计评价标准把“好不好”转化为可以观察、比较或验证的判断依据。",
            whyRelevant: "课程汇报需要说明你的方案为什么成立，而不只是看起来合理。",
            howToUse: "写下 3 条评价标准，并说明每条标准如何被观察或测量。"
        ),
        ResourceCard(
            id: "assumption-mapping",
            title: "Assumption Mapping / 假设识别",
            type: .method,
            relatedStages: [3, 8],
            tags: ["假设", "风险", "边界", "可行性", "验证"],
            summary: "假设地图把项目中的未知判断按重要性和不确定性排序。",
            whyRelevant: "边界和风险阶段都需要看清哪些前提还没有证据支撑。",
            howToUse: "列出 5 个关键假设，优先验证“影响大且不确定”的一项。"
        ),
        ResourceCard(
            id: "progressive-disclosure",
            title: "Progressive Disclosure / 逐级展开",
            type: .designPrinciple,
            relatedStages: [4],
            tags: ["交互", "复杂度", "功能", "信息架构", "概念"],
            summary: "逐级展开通过分层呈现信息，避免用户一次面对过多复杂选择。",
            whyRelevant: "当功能越来越多时，它能帮助你保护核心体验。",
            howToUse: "把功能分成默认可见、按需展开和高级设置三层。"
        ),
        ResourceCard(
            id: "hicks-law",
            title: "Hick's Law / 希克定律",
            type: .designPrinciple,
            relatedStages: [4, 6],
            tags: ["选择", "决策", "复杂度", "约束", "界面"],
            summary: "选择越多，用户做决定通常越慢，界面需要控制同时出现的选项数量。",
            whyRelevant: "它能提醒你在功能拆解时避免把所有能力都塞进第一版。",
            howToUse: "检查核心流程中每一步的选项数量，删掉不服务当前目标的选择。"
        ),
        ResourceCard(
            id: "gestalt-principles",
            title: "Gestalt Principles / 格式塔原则",
            type: .designPrinciple,
            relatedStages: [4],
            tags: ["视觉", "布局", "分组", "界面", "可读性"],
            summary: "格式塔原则解释人们如何通过接近、相似、连续等线索理解界面结构。",
            whyRelevant: "当你准备原型或展示图时，它能提高信息组织的清晰度。",
            howToUse: "检查同类信息是否靠近、样式是否一致、视觉层级是否能被快速扫读。"
        ),
        ResourceCard(
            id: "feedback-loop",
            title: "Feedback Loop / 反馈循环",
            type: .designPrinciple,
            relatedStages: [6],
            tags: ["反馈", "评价", "指标", "迭代", "验证"],
            summary: "反馈循环让用户行为、系统响应和后续改进形成可观察的闭环。",
            whyRelevant: "评价标准不应只停留在结果，也要说明如何回到下一轮设计。",
            howToUse: "为一个关键指标写出：谁提供反馈、何时收集、如何影响下一次迭代。"
        ),
        ResourceCard(
            id: "google-pair-guidebook",
            title: "Google PAIR Guidebook",
            type: .caseStudy,
            relatedStages: [3, 7],
            tags: ["AI", "人机协作", "边界", "可行性", "责任"],
            summary: "PAIR Guidebook 提供以人为中心设计 AI 产品的方法和问题清单。",
            whyRelevant: "如果项目涉及 AI，必须说明系统边界、用户控制和失败处理。",
            howToUse: "用它检查：AI 何时介入、用户如何理解结果、错误输出如何被处理。"
        ),
        ResourceCard(
            id: "notebooklm-audio-overview",
            title: "NotebookLM Audio Overview",
            type: .caseStudy,
            relatedStages: [7],
            tags: ["AI", "案例", "学习", "音频", "原生体验"],
            summary: "NotebookLM 的音频概览展示了 AI 原生学习体验如何把资料转化为可听、可讨论的内容。",
            whyRelevant: "它能启发你思考 AI 不只是生成文本，也可以改变学习材料的呈现方式。",
            howToUse: "分析它把哪些学习动作自动化、哪些判断仍留给用户。"
        ),
        ResourceCard(
            id: "ai-behavior-designer",
            title: "Course Assistant / AI Behavior Designer Framework",
            type: .courseFramework,
            relatedStages: [7],
            tags: ["AI", "助教", "行为", "可行性", "课程"],
            summary: "AI 行为设计关注系统在何时追问、何时建议、何时保持沉默。",
            whyRelevant: "它适合评估课程助教类项目是否真正支持学习过程，而不是替学生完成任务。",
            howToUse: "为你的 AI 写三条行为规则：应该追问什么、推荐什么、避免代替用户做什么。"
        )
    ]
}
